import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {LiveWorkflow} from '../server/live-workflow.ts';
const saved=JSON.parse(readFileSync('docs/cases/live-followup-room-coverage-workflow-20261008.json','utf8'));
const unused=async():Promise<any>=>{throw Error('Unexpected tool');};
test('nearby expansion keeps scope, rejects conflicts, leaves unknown identity unbound, and does not repeat attempted names',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'nearby-flow-')),now=new Date().toISOString();let lookups=0,routes=0;
 const names=['未知地址酒店','已核验酒店','冲突酒店','第四酒店'];const places=names.map((name,i)=>({id:'poi-'+i,name,address:'测试街11号',location:'116.4173,39.9472',city:'北京',source:'poi' as const}));
 const flow=new LiveWorkflow('case',{flySearch:unused,rollingSearch:unused,rollingDetail:unused,jev:unused,places:async()=>({places:[{id:'dest',name:'雍和宫',address:'雍和宫',location:'116.417296,39.947239',city:'北京',source:'poi' as const}],observedAt:now,warnings:[],source:'高德地图 Web 服务',requiresSelection:true}),nearbyHotels:async()=>({source:'高德地图 Web 服务',observedAt:now,query:{location:'116.417296,39.947239',city:'北京',radius:2000},keyword:'酒店',places,discoveryOnly:true,limitations:[]}),rollingLookup:async(input:any):Promise<any>=>{lookups++;const i=names.indexOf(input.name);assert.equal(input.filter.cancelPolicy,'CANCELABLE');return {source:'RollingGo MCP',observedAt:now,hotelId:100+i,name:i===2?'其他酒店':names[i],identity:{hotelId:100+i,name:names[i],address:i===0?null:'测试街11号',verified:i!==0,observedAt:now},rooms:[],filter:input.filter,detailUrl:null};},routes:async()=>{routes++;return {source:'高德地图 Web 服务',observedAt:now,origin:'116.4173,39.9472',destination:'116.417296,39.947239',city:'北京',walking:{minutes:1,meters:10},transits:[],warnings:[]};}},dir);
 const db=new DatabaseSync(join(dir,'case.sqlite'));db.prepare('INSERT INTO runs(payload) VALUES(?)').run(JSON.stringify(saved));db.close();
 try{const first=await flow.expandNearby({runId:saved.id,evidenceHash:saved.evidenceHash});assert.equal(first.kind,'nearby_discovery');assert.equal(Date.parse(first.nearbyDiscovery!.nextRetryAt!)-Date.parse(first.completedAt),15*60_000);assert.equal(first.parentRunId,saved.id);assert.equal(first.candidates.length,2);assert.equal(lookups,3);assert.equal(routes,1);assert.deepEqual(first.policy,saved.policy);assert.deepEqual(first.query,saved.query);assert.equal(first.transactionEnabled,false);assert.equal(first.candidates.find(d=>d.candidate.name===names[0])!.candidate.route,null);assert(first.errors.length);assert.deepEqual(flow.savedRun(saved.id),saved);
 await assert.rejects(flow.expandNearby({runId:saved.id,evidenceHash:saved.evidenceHash}));
 const second=await flow.expandNearby({runId:first.id,evidenceHash:first.evidenceHash});assert.deepEqual(second.nearbyDiscovery?.attemptedNames,[names[3]]);assert.equal(lookups,4);assert.equal(second.parentRunId,first.id);
 }finally{flow.close();rmSync(dir,{recursive:true,force:true});}
});

for(const scope of ['destination','nearby'] as const)test(`nearby discovery refuses stale, future and unzoned ${scope} observations before merchant calls`,async()=>{
 for(const observedAt of [new Date(Date.now()-16*60_000).toISOString(),new Date(Date.now()+60_000).toISOString(),'2026-10-09T00:00:00']){
 const dir=mkdtempSync(join(tmpdir(),'nearby-time-'));let merchantCalls=0,nearbyCalls=0;const now=new Date().toISOString();
 const flow=new LiveWorkflow('case',{flySearch:unused,rollingSearch:unused,rollingDetail:unused,jev:unused,routes:unused,places:async():Promise<any>=>({observedAt:scope==='destination'?observedAt:now,places:[{name:'雍和宫',location:'116.417296,39.947239',source:'poi',id:'dest',address:'雍和宫',city:'北京'}]}),nearbyHotels:async():Promise<any>=>{nearbyCalls++;return {observedAt:scope==='nearby'?observedAt:now,places:[]};},rollingLookup:async():Promise<any>=>{merchantCalls++;throw Error('Must not call');}},dir);
 const db=new DatabaseSync(join(dir,'case.sqlite'));db.prepare('INSERT INTO runs(payload) VALUES(?)').run(JSON.stringify(saved));db.close();
 try{await assert.rejects(flow.expandNearby({runId:saved.id,evidenceHash:saved.evidenceHash}),/地图证据已过期或时间无效/);assert.equal(merchantCalls,0);assert.equal(nearbyCalls,scope==='destination'?0:1);assert.equal(flow.state().running,false);assert.deepEqual(flow.savedRun(saved.id),saved);}finally{flow.close();rmSync(dir,{recursive:true,force:true});}
 }
});
