import {test} from 'node:test';
import assert from 'node:assert/strict';
import {inspectTradeoffs} from '../server/tradeoff-inspection.ts';
import {recordedCandidates,defaultWorkflowPolicy} from '../server/live-workflow.ts';
function data(){const {candidates,asOf}=recordedCandidates();return {candidate:candidates[0],asOf};}
function assessment(candidate:any,action:string){return {options:[{id:'chosen',candidateKey:candidate.key}],nextAction:{choice:action},inspectionLog:[{optionId:'chosen',action,status:'handoff',at:'2026-10-08T00:00:00Z',detail:'proposed'}]} as any;}
test('requested inspection executes then reevaluates; repeated identical tasks are bounded',async()=>{const {candidate,asOf}=data();let queried=0,evaluated=0;const result=await inspectTradeoffs([candidate],defaultWorkflowPolicy,asOf,2,async()=>{evaluated++;return assessment(candidate,'commute');},async()=>{queried++;});assert.equal(queried,1);assert.equal(evaluated,2);assert(result.assessment.inspectionLog.some(e=>e.status==='completed'));});
test('unsupported review inspection hands off without pretending it ran',async()=>{const {candidate,asOf}=data();let queried=0;const result=await inspectTradeoffs([candidate],defaultWorkflowPolicy,asOf,2,async()=>assessment(candidate,'reviews'),async()=>{queried++;});assert.equal(queried,0);assert(result.assessment.inspectionLog.every(e=>e.status==='handoff'));});
test('failed source lookup retains prior evidence and does not repeat',async()=>{const {candidate,asOf}=data();const before=JSON.stringify(candidate);let queried=0;const result=await inspectTradeoffs([candidate],defaultWorkflowPolicy,asOf,2,async()=>assessment(candidate,'rooms'),async()=>{queried++;throw new Error('offline');});assert.equal(queried,1);assert.equal(JSON.stringify(candidate),before);assert(result.assessment.inspectionLog.some(e=>e.status==='failed'));});
test('automatic inspection never exceeds three source actions in one evaluation round',async()=>{const {candidate,asOf}=data();const candidates=Array.from({length:4},(_,i)=>({...structuredClone(candidate),key:'rollinggo:'+i}));let queries=0,evaluations=0;const result=await inspectTradeoffs(candidates,defaultWorkflowPolicy,asOf,2,async()=>assessment(candidates[Math.min(evaluations++,3)],'rooms'),async()=>{queries++;});assert.equal(queries,3);assert.equal(evaluations,4);assert.equal(result.assessment.inspectionLog.filter(e=>e.status==='completed').length,3);});
