import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaultTripDates,readWorkflowDraft,serializeWorkflowDraft} from '../shared/workflow-draft.ts';
import {defaultWorkflowPolicy} from '../shared/workflow-policy.ts';
const query={destination:'北京',poi:'雍和宫',checkIn:'2026-10-09',checkOut:'2026-10-10',adultCount:2,roomCount:1,childCount:0,size:10,searchRadiusMeters:2000};
test('default trip dates follow Shanghai midnight and calendar boundaries',()=>{assert.deepEqual(defaultTripDates(new Date('2026-12-31T16:30:00Z')),{checkIn:'2027-01-02',checkOut:'2027-01-03'});assert.deepEqual(defaultTripDates(new Date('2028-02-28T12:00:00Z')),{checkIn:'2028-02-29',checkOut:'2028-03-01'});});
test('a valid saved draft restores exact preferences but does not contain consent or transaction authority',()=>{const policy={...defaultWorkflowPolicy,idealBudgetCents:50000,priorities:'Sleep matters most'};const serialized=serializeWorkflowDraft(query,policy)!;const draft=readWorkflowDraft(serialized)!;assert.deepEqual(draft.query,query);assert.deepEqual(draft.policy,policy);assert(!serialized.includes('confirmed'));assert(!serialized.includes('transactionEnabled'));});
test('corrupt drafts, invalid budgets, dates or extra permission fields cannot restore',()=>{assert.equal(readWorkflowDraft('broken'),null);assert.equal(serializeWorkflowDraft(query,{...defaultWorkflowPolicy,idealBudgetCents:70000}),null);assert.equal(serializeWorkflowDraft({...query,checkIn:'2026-02-30'},defaultWorkflowPolicy),null);const raw=JSON.parse(serializeWorkflowDraft(query,defaultWorkflowPolicy)!);assert.equal(readWorkflowDraft(JSON.stringify({...raw,confirmed:true})),null);assert.equal(serializeWorkflowDraft({...query,adultCount:0},defaultWorkflowPolicy),null);});
test('past saved dates remain visible rather than silently changing the users trip',()=>{const old={...query,checkIn:'2020-01-01',checkOut:'2020-01-02'};assert.deepEqual(readWorkflowDraft(serializeWorkflowDraft(old,defaultWorkflowPolicy))?.query,old);});
