import {inspectionHandoffOption} from './inspection-handoff.ts';
import type {WorkflowResult} from './live-workflow.ts';
import type {InspectionSelection} from './tradeoffs.ts';
export function inspectionBrief(result:WorkflowResult|null,selection:InspectionSelection|null|undefined,context:Parameters<typeof inspectionHandoffOption>[2]&{selectionValid:boolean},language:'zh'|'en'='en'):string|null{
 if(!context.selectionValid)return null;
 const option=inspectionHandoffOption(result,selection,context);if(!option||!result)return null;
 const hotel=result.candidates.find(d=>d.candidate.key===option.candidateKey)!.candidate,room=hotel.rooms.find(r=>r.ratePlanId===option.ratePlanId)!;
 const text=(zh:string,en:string)=>language==='zh'?zh:en;
 let link='';try{const url=new URL(hotel.detailUrl??'');if(url.protocol==='https:'&&!url.username&&!url.password)link=url.href;}catch{}
 return [text('StayPilot 平台核验清单（不是订单）','StayPilot merchant verification brief (not an order)'),text('本清单只交接待核验方案，不证明可订、成交或购买权限。','This transfers a provisional option only, not bookability, a completed booking or purchase authority.'),text('导出时间','Export time')+': '+new Date(context.now).toISOString(),text('记录 / 方案','Run / option')+': '+result.id+' / '+option.id,text('酒店 / 平台','Hotel / platform')+': '+hotel.name+' / '+hotel.source,text('地址','Address')+': '+hotel.address,text('住宿条件','Stay conditions')+': '+result.query.checkIn+' -> '+result.query.checkOut+'; '+result.query.adultCount+' adults; 1 room; 0 children',text('房型 / 报价ID','Room / rate-plan ID')+': '+room.roomName+' / '+room.ratePlanId,text('床型 / 餐食','Bed / meal')+': '+(room.bedType??'unknown')+' / '+(room.mealType??'unknown'),text('房型观察时间','Room observed at')+': '+room.sourceObservedAt,text('展示估价 / 原预算上限','Display estimate / original budget ceiling')+': CNY '+(option.priceCents!/100).toFixed(2)+' / CNY '+(result.policy.budgetCents/100).toFixed(2),text('已观察的取消截止（仍需商户确认）','Observed cancellation deadline (verify with merchant)')+': '+(room.cancelUntil??'unknown'),text('偏好重点','Personal priorities')+': '+(result.policy.priorities??'not specified'),text('明确不可接受的评论问题','Explicitly unacceptable review issues')+': '+(result.policy.unacceptable.join(', ')||'none specified'),text('必需设施 / 窗型要求','Required facilities / window requirement')+': '+((result.policy.requiredAmenities??[]).join(', ')||'none specified')+' / '+result.policy.window,text('取消与通勤范围','Cancellation and commute limits')+': '+(result.policy.requireCancelable?'free cancellation required':'verify cancellation terms')+'; walk '+result.policy.walkMinutes+' min; direct metro '+(result.policy.allowMetro?result.policy.metroMinutes+' min':'not authorized'),text('需核验：含税总价和全部必付费用、库存、完整取消费用与退款规则，以及日期、人数、房型、床型和餐食是否一致。','Verify: tax-inclusive total and all mandatory charges, inventory, full cancellation fees and refund rules, and matching dates, guests, room, bed and meals.'),text('原硬底线及评论偏好仍适用；不能因商户跳转而放宽。','Original hard requirements and review preferences remain applicable; merchant handoff does not relax them.'),text('证据缺口','Evidence gaps')+':',...option.gaps.map(g=>'- '+g),...(link?[text('商户详情链接','Merchant detail link')+': '+link]:[]),text('历史清单不会自动更新；行动前需重新核验。','This saved brief does not update automatically. Refresh evidence before acting.')].join('\n');
}
