import type {JevChoice} from './jev';
import type {WorkflowRoom} from './live-workflow';
export type EvidenceRef={id:string;hotelKey:string;kind:'room'|'route'|'reviews'|'facilities';sourceUrl:string|null;observedAt:string;method:'api'|'web_history'|'web_capture';};
export type TradeoffChange={field:'budget'|'commute'|'window'|'rating'|'newness';from:number|string;to:number|string;withinAuthorization:boolean};
export type TradeoffOption={offer?:Pick<WorkflowRoom,'ratePlanName'|'bedType'|'mealAmount'|'mealType'|'cancelable'|'cancellationStatus'|'cancelUntil'|'onRequest'|'maxOccupancy'|'windowType'>;id:string;candidateKey:string;hotelName:string;roomName:string;ratePlanId:string;observedAt:string;status:'within_bounds'|'requires_confirmation'|'blocked';idealMatch:boolean;priceCents:number|null;priceBasis:'display_estimate';routeMode:'walk'|'metro'|'unknown';minutes:number|null;risk:number|null;changes:TradeoffChange[];hardViolations:string[];gaps:string[];evidence:EvidenceRef[];facts:string[]};
export type TradeoffAssessment={evidenceHash:string;policyVersion:string;status:'ideal_available'|'single_option'|'needs_evidence'|'jev_recommended'|'uncertain'|'no_match'|'model_unavailable';scope:'authorized'|'confirmation_required'|'none';preferredOptionId:string|null;options:TradeoffOption[];model:string|null;observedAt:string;choice:JevChoice|null;basis:JevChoice|null;nextAction:JevChoice|null;usage:{input_tokens:number;output_tokens:number}|null;reason:string;inspectionLog:{optionId:string|null;action:string;status:'completed'|'handoff'|'failed';at:string;detail:string}[];};
export type QuoteRecheck={baseline?:{kind:'original'|'recheck';recheckId?:string;skippedAttempts:number};id:string;runId:string;candidateKey:string;hotelName:string;ratePlanId:string;queryKey:string;checkedAt:string;beforeObservedAt:string;afterObservedAt:string|null;status:'unchanged'|'price_changed'|'terms_changed'|'not_found'|'failed';before:WorkflowRoom;after:WorkflowRoom|null;deltaCents:number|null;reason:string;transactionEnabled:false};

export type InspectionSelection={id:string;runId:string;optionId:string;evidenceHash:string;policyVersion:string;hotelName:string;roomName:string;selectedAt:string;purpose:'inspection_only';transactionEnabled:false};
