import {z} from 'zod';
import type {WorkflowPolicy} from './live-workflow.ts';
import type {ReviewIssue} from './real-agent.ts';
const issues:ReviewIssue[]=['noise','hygiene','smell','maintenance','service','space','security'];
export const defaultWorkflowPolicy:WorkflowPolicy={budgetCents:60000,walkMinutes:20,metroMinutes:40,allowMetro:true,window:'preferred',requireCancelable:true,weights:{noise:3,hygiene:3,smell:1,maintenance:1,service:1,space:1,security:3},unacceptable:[]};
export const policySchema=z.object({budgetCents:z.number().int().min(1).max(100000000),idealBudgetCents:z.number().int().min(1).optional(),priorities:z.string().max(1500).optional(),preferredRating:z.number().min(0).max(5).nullable().optional(),minimumRating:z.number().min(0).max(5).nullable().optional(),preferredYear:z.number().int().min(1900).max(2100).nullable().optional(),allowOlder:z.boolean().optional(),allowLowerRating:z.boolean().optional(),allowWindowRelaxation:z.boolean().optional(),requiredAmenities:z.array(z.string().trim().min(1).max(80)).max(10).optional(),walkMinutes:z.number().int().min(1).max(180),metroMinutes:z.number().int().min(1).max(240),allowMetro:z.boolean(),window:z.enum(['preferred','required','any']),requireCancelable:z.boolean(),weights:z.object({noise:z.number().min(0).max(5),hygiene:z.number().min(0).max(5),smell:z.number().min(0).max(5),maintenance:z.number().min(0).max(5),service:z.number().min(0).max(5),space:z.number().min(0).max(5),security:z.number().min(0).max(5)}).strict(),unacceptable:z.array(z.enum(issues as [ReviewIssue,...ReviewIssue[]])).max(7)}).strict().superRefine((policy,ctx)=>{
 if((policy.idealBudgetCents??policy.budgetCents)>policy.budgetCents)ctx.addIssue({code:"custom",path:["idealBudgetCents"],message:"Ideal spending cannot exceed the maximum budget."});
 if(policy.minimumRating!=null&&policy.preferredRating!=null&&policy.minimumRating>policy.preferredRating)ctx.addIssue({code:"custom",path:["minimumRating"],message:"The hard minimum rating cannot exceed the preferred rating."});
});
