import {useEffect,useState,type ReactNode} from 'react';
import {pick} from './i18n';
type Access={required:boolean;authenticated:boolean};
export function AccessGate({children}:{children:ReactNode}){
 const [state,setState]=useState<Access|null>(null),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(false),[limited,setLimited]=useState(false);
 useEffect(()=>{const controller=new AbortController();void fetch('/api/access/state',{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(10000)])}).then(async response=>{if(!response.ok)throw Error('Access status unavailable');const data=await response.json();if(typeof data.required!=='boolean'||typeof data.authenticated!=='boolean')throw Error('Invalid access status');if(!controller.signal.aborted)setState(data);}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[]);
 useEffect(()=>{if(!state?.required)return;let active=true,pending=false;const controller=new AbortController();async function check(){if(pending)return;pending=true;try{const response=await fetch('/api/access/state',{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(10000)])});if(!response.ok)throw Error('Access unavailable');const data=await response.json();if(typeof data.required!=='boolean'||typeof data.authenticated!=='boolean')throw Error('Invalid access');if(active)setState(data);}catch{if(active)setError(true);}finally{pending=false;}}const timer=setInterval(()=>void check(),30000);const visible=()=>{if(document.visibilityState==='visible')void check();};document.addEventListener('visibilitychange',visible);return()=>{active=false;clearInterval(timer);controller.abort();document.removeEventListener('visibilitychange',visible);};},[state?.required]);
 async function login(){setBusy(true);setError(false);setLimited(false);try{const response=await fetch('/api/access/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!response.ok){setLimited(response.status===429);throw Error('Login failed');}setState({required:true,authenticated:true});setPassword('');}catch{setError(true);}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{const response=await fetch('/api/access/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!response.ok)throw Error('Logout failed');setState({required:true,authenticated:false});setPassword('');}catch{setError(true);}finally{setBusy(false);}}
 if(state?.authenticated)return <>{state.required&&<div style={{padding:'60px 16px 8px',textAlign:'right'}}><button className="secondary" disabled={busy} onClick={()=>void logout()}>{pick('退出访问','Sign out')}</button>{error&&<span role="alert">{pick('请求未完成，请重试。','The request did not complete. Retry.')}</span>}</div>}{children}</>;
 return <main style={{maxWidth:480,margin:'12vh auto',padding:24}}><h1>StayPilot</h1>{state?.required?<form onSubmit={event=>{event.preventDefault();void login();}}><p>{pick('请输入此部署的访问密码。登录不会授权购买。','Enter the access password for this deployment. Signing in does not authorize purchases.')}</p><label>{pick('访问密码','Access password')}<input type="password" autoComplete="current-password" required maxLength={1024} value={password} disabled={busy} onChange={event=>setPassword(event.target.value)}/></label><button disabled={busy}>{pick('登录','Sign in')}</button></form>:<p role="status">{pick('正在检查访问状态…','Checking access…')}</p>}{error&&<p role="alert">{limited?pick('尝试次数过多，请五分钟后重试。','Too many attempts. Retry in five minutes.'):pick('无法完成访问验证，请检查密码或连接后重试。','Access verification failed. Check your password or connection and retry.')}</p>}{!state&&error&&<button onClick={()=>location.reload()}>{pick('重新载入','Reload')}</button>}</main>;
}
