import {useEffect,useState} from 'react';
import type {MapPlace,MapRoutes} from '../shared/amap';
async function request<T>(path:string,body?:unknown):Promise<T>{const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw new Error(data.error||'查询未成功');return data;}
export default function AmapRoutes({hotelAddress}:{hotelAddress:string}){
 const [city,setCity]=useState('杭州'),[origin,setOrigin]=useState('杭州市西湖区文三路168号'),[destination,setDestination]=useState('湖滨银泰in77');
 const [fromPlaces,setFromPlaces]=useState<MapPlace[]>([]),[toPlaces,setToPlaces]=useState<MapPlace[]>([]),[fromId,setFromId]=useState(''),[toId,setToId]=useState(''),[confirmed,setConfirmed]=useState(false);
 const [routes,setRoutes]=useState<MapRoutes|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[warnings,setWarnings]=useState<string[]>([]);
 const [integration,setIntegration]=useState<{model:{configured:boolean;name:string|null};amap:{configured:boolean}}|null>(null);
 const reset=()=>{setFromPlaces([]);setToPlaces([]);setFromId('');setToId('');setConfirmed(false);setRoutes(null);setWarnings([]);setError('');};
 useEffect(()=>{void request<typeof integration>('/api/live/integrations').then(setIntegration).catch(()=>{});},[]);
 useEffect(()=>{if(hotelAddress){setOrigin(hotelAddress);reset();document.getElementById('route-verification')?.scrollIntoView({behavior:'smooth'});}},[hotelAddress]);
 async function find(){setBusy(true);reset();try{const [from,to]=await Promise.all([request<{places:MapPlace[];warnings:string[]}>('/api/live/amap/places',{query:origin,city}),request<{places:MapPlace[];warnings:string[]}>('/api/live/amap/places',{query:destination,city})]);setFromPlaces(from.places);setToPlaces(to.places);setWarnings([...from.warnings,...to.warnings]);if(!from.places.length||!to.places.length)setError('一个地点没有匹配结果，请补全酒店地址或具体目的地。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function calculate(){const from=fromPlaces.find(p=>p.id===fromId),to=toPlaces.find(p=>p.id===toId);if(!from||!to||!confirmed)return;setBusy(true);setError('');setRoutes(null);try{setRoutes(await request<MapRoutes>('/api/live/amap/routes',{origin:from.location,destination:to.location,city,confirmed:true}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const placeSelect=(label:string,places:MapPlace[],id:string,setId:(v:string)=>void)=><label>{label}<select value={id} disabled={busy} onChange={e=>{setId(e.target.value);setConfirmed(false);setRoutes(null);}}><option value="">请选择与实际地点一致的位置</option>{places.map(p=><option key={p.id} value={p.id}>{p.name} · {p.address} · {p.location}</option>)}</select></label>;
 return <section className="panel route-verification" id="route-verification"><div className="section-heading"><div><span className="section-kicker">AMAP / COMMUTE EVIDENCE</span><h2>距离不只看地图上的直线。</h2><p className="hint">先确认酒店与目的地的具体位置，再核验步行、地铁与公交路线。</p></div><span className="pill">{integration?.amap.configured?'高德已配置':'地图状态待确认'}</span></div><p className="hint">需求理解：{integration?.model.configured?integration.model.name:'规则模式'} · 地图密钥仅保存在服务端</p><div className="route-fields"><label>路线城市<input value={city} disabled={busy} onChange={e=>{setCity(e.target.value);reset();}}/></label><label>酒店或起点地址<input value={origin} disabled={busy} onChange={e=>{setOrigin(e.target.value);reset();}}/></label><label>具体目的地<input value={destination} disabled={busy} onChange={e=>{setDestination(e.target.value);reset();}}/></label><button className="btn" disabled={busy||!city.trim()||!origin.trim()||!destination.trim()} onClick={()=>void find()}>{busy?'正在查询…':'查找并核对地图位置'}</button></div>{(fromPlaces.length>0||toPlaces.length>0)&&<div className="route-selection">{placeSelect('确认酒店位置',fromPlaces,fromId,setFromId)}{placeSelect('确认目的地位置',toPlaces,toId,setToId)}<label className="checkbox-label"><input type="checkbox" checked={confirmed} disabled={busy||!fromId||!toId} onChange={e=>setConfirmed(e.target.checked)}/>我已核对两个具体地点，使用以上坐标计算路线。</label><button className="btn primary" disabled={busy||!fromId||!toId||!confirmed} onClick={()=>void calculate()}>核验实际通勤</button></div>}{error&&<p role="alert" className="conflict-text">{error}</p>}{warnings.map((w,i)=><p className="hint" key={i}>{w}</p>)}{routes&&<><p className="hint">来源：{routes.source} · 获取时间 {new Date(routes.observedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})} · 当前路线估计，不保证入住日的班次或运营时间。</p><div className="route-results"><article><span className="section-kicker">WALKING</span><h3>{routes.walking?`步行 ${routes.walking.minutes} 分钟`:'步行路线未知'}</h3><p>{routes.walking?`${(routes.walking.meters/1000).toFixed(2)} 公里`:'无法用于证明距离满足要求'}</p></article>{routes.transits.map((t,i)=><article key={i}><span className="pill">{t.classification}</span><h3>{t.minutes} 分钟</h3><p>约 {(t.meters/1000).toFixed(2)} 公里 · {t.transfers===null?'换乘情况未知':`${t.transfers} 次换乘`}{t.walkingMeters!==null?` · 含步行 ${t.walkingMeters} 米`:''}</p>{t.lines.map((l,j)=><p key={j}><strong>{l.name}</strong><br/>{l.departure} → {l.arrival}</p>)}<small>{t.metroDirect?'一个已识别的地铁线路，包含步行接驳':'此路线不能视为地铁直达'}</small></article>)}</div>{routes.warnings.map((w,i)=><p className="conflict-text" key={i}>{w}</p>)}</>}<p className="hint">地图用于核验通勤，不代表房型、设施或住宿可订性已通过。真实报价资料补齐前仍阻止自动成交。</p></section>;
}
