export const english:Record<string,string> = {
  "测试资金已充值": "Test funds have been topped up",
  "充值金额（元）": "Top-up amount (CNY)",
  "确认充值": "Confirm top-up",
  "授权额度与钱包余额分别审核，退款到账后才能再次使用。": "Authorization limit and wallet balance are verified separately; reuse is permitted only after the refund is credited.",
  "你的酒店决策员": "Your hotel decision agent",
  "智能体决策模式": "Agent decision mode",
  "规则驱动": "Rule-driven",
  "模型辅助": "Model-assisted",
  "从偏好出发，比较三个平台，找到预算内适合你的住宿。": "Start from your preferences, compare three platforms, and find budget-friendly accommodation that suits you.",
  "已观察": "Observed",
  "次": "times",
  "每 30 仿真分钟检查": "Check every 30 simulation minutes",
  "上次执行": "Last run",
  "智能体已启动，请查看浏览记录": "The agent is running. Please review the browsing history.",
  "正在浏览市场": "Browsing the market",
  "按授权查找并预订": "Search and book within your authorized limit",
  "持续监控已关闭": "Continuous monitoring is off",
  "持续监控已开启": "Continuous monitoring is on",
  "关闭持续监控": "Turn off continuous monitoring",
  "开启持续监控": "Turn on continuous monitoring",
  "先确认偏好与授权 →": "Confirm preferences and authorization first →",
  "当前进度：": "Current progress:",
  "打开逐步流程 →": "Open step-by-step process →",
  "三个平台，同一场选择": "Three platforms, one selection",
  "等待网页观察": "Waiting for webpage observation",
  "已观察最低总价": "Observed lowest total price",
  "授权内候选": "Candidates within authorized limit",
  "规则排除": "Excluded by rules",
  "交易记录": "Transaction records",
  "只展示已经浏览的报价，不预知未来市场。": "Only displays previously viewed quotes, and does not predict future market prices.",
  "比较候选 →": "Compare candidates →",
  "决策动态": "Decision updates",
  "全部记录 ↗": "All records ↗",
  "决策从授权开始": "Decisions start with authorization",
  "确认偏好后，智能体的每一次观察和判断都会记录在这里。": "After confirming your preferences, all observations and judgments made by the agent will be recorded here.",
  "酒店房间氛围示意图": "Hotel room ambiance schematic",
  "已锁定住宿 ·": "Locked accommodation ·",
  "含税总价": "Total price (tax included)",
  "查看订单 →": "View order →",
  "可回放的市场场景": "Replayable market scenarios",
  "重置场景会清空当前订单、授权和流水。每个场景使用同一仿真时钟。": "Resetting the scenario will clear current orders, authorizations, and transaction records. Each scenario uses the same simulation clock.",
  "演示场景": "Demo scenario",
  "确定重置仿真？当前订单、授权和钱包记录将被清空。": "Confirm simulation reset? Current orders, authorizations, and wallet records will be cleared.",
  "仿真已重置": "Simulation has been reset",
  "重置场景": "Reset scenario",
  "意向酒店与跨平台报价": "Target hotels and cross-platform quotes",
  "先按偏好档位，再按评论风险、含税总价和通勤时间排序。": "Sort first by preference tier, then by review risk, total tax-included price, and commute time.",
  "重新浏览比较": "Re-browse and compare",
  "还没有意向酒店": "No target hotels yet",
  "启动一次决策后，已观察的酒店、评论证据与排除理由会显示在这里。": "After starting a decision round, observed hotels, review evidence, and exclusion reasons will be displayed here.",
  "决策与交易记录": "Decision and transaction records",
  "导出完整日志 ↗": "Export full log ↗",
  "搜索决策记录": "Search decision records",
  "搜索标题、理由或订单": "Search titles, reasons, or orders",
  "记录类型": "Record type",
  "全部类型": "All types",
  "仿真": "Simulation",
  "实际": "Actual",
  "哈希": "Hash",
  "核验数据与授权依据": "Verify data and authorization basis",
  "查询未成功": "Query failed",
  "杭州": "Hangzhou",
  "杭州市西湖区文三路168号": "No. 168 Wensan Road, Xihu District, Hangzhou",
  "湖滨银泰in77": "Hubin Yintai IN77",
  "有一个地点未找到。请补全酒店地址或更换具体目的地后重试。": "One location could not be found. Please complete the hotel address or change the specific destination and try again.",
  "请选择正确的地点": "Please select the correct location.",
  "核对通勤路线": "Verify commute route",
  "步行 · 地铁 · 公交": "Walking · Subway · Bus",
  "从酒店出发，需要多久？": "How long does it take from the hotel?",
  "先找到并确认两个地点，再查看实际路线。": "First find and confirm both locations, then view the actual route.",
  "高德已配置": "Amap is configured",
  "高德未配置": "Amap is not configured",
  "地图状态待确认": "Map status pending confirmation",
  "城市": "City",
  "如：杭州": "e.g. Hangzhou",
  "酒店或出发地址": "Hotel or departure address",
  "填写酒店完整地址": "Enter the full hotel address",
  "要去的地点": "Destination",
  "如：湖滨银泰 in77": "e.g. Hubin Yintai IN77",
  "正在查询…": "Querying…",
  "查找地点": "Search location",
  "确认地图匹配的地点": "Confirm the location matched on the map",
  "同名地点可能有多个。请按名称和地址选择，避免算错路线。": "There may be multiple locations with the same name. Please select by name and address to avoid incorrect route calculation.",
  "出发地点": "Departure location",
  "到达地点": "Arrival location",
  "我已确认这两个地点的位置正确。": "I have confirmed the positions of these two locations are correct.",
  "正在计算…": "Calculating…",
  "查看通勤时间": "View commute time",
  "选择出发与到达地点，并确认位置后，即可计算路线。": "Select departure and arrival locations, and confirm their positions to calculate the route.",
  "通勤路线": "Commute route",
  "高德实时路线估计": "Amap real-time route estimate",
  "步行": "Walking",
  " 分钟": " minutes",
  "暂无路线": "No route available at the moment",
  "约 ": "Approx. ",
  " 公里": " km",
  "本次没有返回步行路线，无法确认步行距离。": "No walking route was returned this time, so walking distance cannot be confirmed.",
  "分钟": "minutes",
  "换乘情况未知": "Transfer status unknown",
  " 次换乘": " transfers",
  " · 步行 ": " · Walking ",
  " 米": " m",
  "单条地铁线路，含步行接驳": "Single subway line, with walking transfer",
  "包含换乘或其他交通方式，不能视为地铁直达": "Includes transfers or other transport modes, cannot be considered a direct subway route.",
  "查看线路与站点": "View route and stops",
  "全程约": "Total approx.",
  "公里": "km",
  "本次未返回公交或地铁方案，可尝试更换具体地点后重查。": "No bus or subway route was returned this time. You can try changing the specific location and search again.",
  "查询于": "Queried at",
  "（上海时间）。这是当前估计，入住当天的班次与运营时间需再确认。": "(Shanghai Time). This is a current estimate; service schedules and operating hours on your check-in day need to be confirmed separately.",
  "查看数据来源与地图位置": "View data source and map location",
  "路线来源：": "Route source: ",
  "高德地图 Web 服务": "Amap Web Service",
  "。地图用于核对通勤，酒店房型、设施和可订状态仍需另外确认。": ". The map is used to verify commute routes; hotel room types, facilities and booking availability still need to be confirmed separately.",
  "出发：": "Departure: ",
  "· 坐标": "· Coordinates",
  "到达：": "Arrival: ",
  "需求理解：": "Interpreted request: ",
  "规则模式": "Rule mode",
  "。地图密钥仅保存在服务端。": ". Map keys are stored only on the server.",
  "已预订": "Booked",
  "等待启动": "Pending Launch",
  "住得合适，选得轻松": "Stay comfortably, choose with ease",
  "我的住宿助手": "My Accommodation Assistant",
  "主导航": "Main Navigation",
  "真实酒店查询": "Real Hotel Search",
  "飞猪酒店查询": "Fliggy Hotel Search",
  "RollingGo 房型核验": "RollingGo Room Type Verification",
  "完整只读核验": "Full Read-Only Verification",
  "真实数据 · 只读查询": "Real Data · Read-Only Search",
  "体验仿真平台": "Experience Simulation Platform",
  "平台": "Platform",
  "每一步，都由你做主": "You're in control every step of the way",
  "先确认偏好与预算，再开始自动预订。": "Confirm your preferences and budget first before starting automatic booking.",
  "测试环境 · 上海时间": "Test Environment · Shanghai Time",
  "把选酒店，变简单。": "Simplify hotel selection.",
  "你的住宿安排，一目了然。": "Your accommodation arrangements are clear at a glance.",
  "按你的偏好，找到合适的酒店。": "Find a hotel that suits your preferences.",
  "看看哪家，更适合你。": "See which hotel is a better fit for you.",
  "订单与决策，都在这里。": "All your orders and decisions are right here.",
  "浏览截图": "View Screenshot",
  "打开浏览截图 ↗": "Open View Screenshot ↗",
  "尚无决策记录": "No Decision Records Yet",
  "授权、浏览、审核、预订与退款都会生成可导出的事件。": "Authorization, browsing, review, booking, and refund actions all generate exportable events.",
  "真实浏览截图": "Real View Screenshot",
  "当前仿真网页": "Current Simulated Webpage",
  "截图": "Screenshot",
  "演示时间工具": "Demo Time Tool",
  "运行中": "Running",
  "已暂停": "Paused",
  "当前仿真时间": "Current Simulated Time",
  "决策执行中 · 时钟暂缓": "Decision Execution in Progress · Clock Paused",
  "仿真速度": "Simulation Speed",
  "× 速度": "× Speed",
  "暂停": "Pause",
  "开始时钟": "Start Clock",
  "+30 分钟": "+30 Minutes",
  "+1 小时": "+1 Hour",
  "推进仿真时间可体验价格变化和退款到账，真实酒店查询使用独立的真实时间。": "Advancing simulation time lets you experience price changes and refund posting; real hotel queries use independent real-world time.",
  "StayPilot · 让预算、偏好与交易边界保持一致": "StayPilot · Align your budget, preferences, and transaction boundaries",
  "栖": "Lodging",
  "住": "Stay",
  "泊": "Parking",
  "服务暂时不可用，请稍后重试": "Service temporarily unavailable, please try again later.",
  "操作未完成": "Action incomplete",
  "正在加载住宿助手…": "Loading accommodation assistant…",
  "体验模式 · 酒店与资金为测试数据，图片为氛围示意": "Experience mode · Hotels and funds are test data, images are for ambiance reference.",
  "操作被交易规则阻止": "Action blocked by transaction rules.",
  "暂时无法连接服务": "Temporarily unable to connect to service.",
  "重新连接": "Reconnect",
  "关闭提示": "Dismiss prompt",
  "选酒店流程": "Hotel selection process",
  "任务总览": "Task overview",
  "偏好与授权": "Preferences and authorization",
  "酒店比较": "Hotel comparison",
  "订单与决策": "Bookings and decisions",
  "授权已撤销": "Authorization revoked",
  "等待授权": "Awaiting authorization",
  "正在查找": "Searching",
  "价格监控中": "Price monitoring in progress",
  "所有商户与资金均为仿真数据": "All merchants and funds are simulated data.",
  "等待你的授权，然后开始浏览市场。": "Awaiting your authorization to start browsing the market.",
  "正在平台 A 建立意向清单并核对评论。": "Building a shortlist of intended properties and cross-verifying reviews on Platform A.",
  "正在其他平台核验同酒店与新候选。": "Verifying the same hotel and new candidates on other platforms.",
  "正在读取酒店网页与评论，并跨平台核验报价。": "Reading hotel web pages and reviews, and cross-verifying quotes across platforms.",
  "正在对照授权底线、评论风险与预算筛选酒店。": "Filtering hotels against your authorized limits, review risk, and budget.",
  "正在重新核验报价、余额与授权，再提交预订。": "Re-verifying quotes, balance, and authorization before submitting the booking.",
  "持续监控已开启，将在取消期限内寻找更好的选择。": "Continuous monitoring is enabled, and we will look for better options within the cancellation window.",
  "本轮决策已完成，完整依据已记录。": "This round of decision-making is complete, and full supporting basis has been recorded.",
  "交易状态需要核验，后续购买已冻结。": "Transaction status requires verification, and subsequent purchases have been frozen.",
  "首次预订截止已到，已停止新购买。": "First booking deadline has passed, and new purchases have been stopped.",
  "正在按授权查找酒店，符合条件后将自动使用测试资金预订。": "Searching for hotels per authorized parameters, and will automatically book with test funds once requirements are met.",
  "你的预算与底线，始终优先。": "Your budget and limits are always prioritized.",
  "跟随智能体进度": "Track agent progress",
  "酒店选择步骤": "Hotel selection steps",
  "已确认": "Confirmed",
  "有效授权": "Valid authorization",
  "已读网页": "Read web pages",
  "已排序": "Sorted",
  "已有确认订单": "Existing confirmed booking",
  "查看任务进度、测试资金和最新动态。": "View task progress, test funds, and latest updates.",
  "底线不妥协，能放宽的条件由你排序。": "Non-negotiable bottom line; flexible conditions ranked by you.",
  "相同入住条件下，比较总价、取消政策与评论。": "Under same stay conditions, compare total price, cancellation policy, and reviews.",
  "查看预订结果、退款状态与每一次选择的依据。": "View booking results, refund status, and basis for each choice.",
  "当前住宿任务": "Current accommodation task",
  "的安心住宿": "Safe accommodation",
  "位住客 ·": "guests ·",
  "间房 ·": "rooms ·",
  "评分 ≥": "Rating ≥",
  "步行 ≤": "Walking ≤",
  "年后开业": "Opening year",
  "首次预订截止": "First booking deadline",
  "查看授权": "View authorization",
  "测试钱包": "Test wallet",
  "充值测试资金 ↗": "Top up test funds ↗",
  "可用余额": "Available balance",
  "住宿预算": "Accommodation budget",
  "已占款": "Funds held",
  "待退款": "Pending refund",
  "助手会读取酒店与评论，比较后按授权自动预订。": "Assistant reads hotel info and reviews, compares, and auto-books per authorization.",
  "首选与备选都有依据，详细证据可随时展开。": "Primary and backup options both have basis; detailed evidence available anytime.",
  "以商户确认订单和实际资金状态为准。": "Subject to merchant order confirmation and actual fund status.",
  "可取消期限内，按已确认的条件寻找更省的方案。": "Within cancellation period, find cheaper options per confirmed conditions.",
  "人 /": "person /",
  "间": "room",
  "住宿总预算": "Total accommodation budget",
  "· 测试余额": "· Test balance",
  "修改行程": "Modify itinerary",
  "按你的偏好，查找并预订": "Search and book per your preferences",
  "正在实际打开网页、读取酒店详情与评论。": "Actually opening webpage, reading hotel details and reviews.",
  "先查看酒店与住客评论，再跨平台比较；满足你的条件后，会自动使用测试资金预订。": "First check hotel and guest reviews, then cross-platform compare; auto-books with test funds once conditions met.",
  "总预算": "Total budget",
  "已允许不可取消房": "Non-cancellable rooms allowed",
  "只订可取消房": "Book cancellable rooms only",
  "测试资金": "Test funds",
  "正在浏览…": "Browsing…",
  "好住处，从你的偏好出发": "Good accommodation, based on your preferences",
  "点击上方按钮，助手会开始查找酒店。酒店信息和评论会陆续出现在这里。": "Click button above, assistant starts searching hotels. Hotel info and reviews appear here.",
  "先核验质量，再比同条件总价": "Verify quality first, then compare total price under same conditions",
  "排序：授权底线 → 最少降级 → 个人差评风险 → 含税总价 → 通勤时间。不可取消与限时取消分别标注，不因低价替换取消权限。": "Ranking: authorization bottom line → least downgrade → personal negative review risk → total price with tax → commute time. Non-cancellable and limited-time cancellable marked separately; cancellation rights not replaced by low price.",
  "报价绑定": "Quote binding",
  "至": "to",
  "人、": "person,",
  "间、": "room,",
  "。评分保留平台原值，评论样本量分别展示。": ". Ratings keep original platform values; review sample sizes shown separately.",
  "尚无跨平台观察": "No cross-platform observation yet",
  "先启动智能体，等待它实际读取三个网页。": "Start agent first, wait for it to actually read three webpages.",
  "已取得商户确认订单": "Merchant order confirmation obtained",
  "截止无解，停止新增购买": "Deadline unsolvable, stop new purchases",
  "已记录实际阻断": "Actual block recorded",
  "等待最终成交核验": "Waiting for final transaction verification",
  "本轮候选首选：": "This round primary candidate:",
  "；候选排序不能替代商户订单确认。": "; candidate ranking cannot replace merchant order confirmation.",
  "购买授权": "Purchase authorization",
  "未确认或已撤销": "Unconfirmed or revoked",
  "含税住宿预算": "Accommodation budget with tax",
  "实际可用测试余额": "Actual available test balance",
  "当前占款 / 上限": "Current funds held / limit",
  "最近阻断记录：": "Recent block records:",
  "提交时后端重新检查报价、库存、授权版本及期限；真实飞猪成交入口仍被禁止，这里是完整测试交易。": "Backend rechecks quote, inventory, authorization version and validity upon submission; real Fliggy transaction entry still prohibited, this is complete test transaction.",
  "核验完整决策与网页截图": "Verify complete decision and webpage screenshots",
  "先获得确认订单": "Obtain order confirmation first",
  "不可取消，住宿已锁定": "Non-cancellable, accommodation locked",
  "退款或异常待处理，冻结换订": "Refund or exception pending, freeze rebooking",
  "继续寻找可取消的更优方案": "Continue searching for better cancellable options",
  "当前住宿可取消，等待启用监控": "Current accommodation cancellable, waiting to enable monitoring",
  "按授权购买了不可取消房，停止换订。": "Purchased non-cancellable room per authorization, stop rebooking.",
  "新酒店档位和评论风险不得变差；同时达到净省金额与比例门槛，先确认新单，再退旧单。": "New hotel tier and review risk must not worsen; simultaneously meet net savings amount and ratio thresholds, confirm new order first, then cancel old.",
  "没有订单时不能宣称已订后优化。": "Cannot claim post-booking optimization without order.",
  "优化截止": "Optimization deadline",
  "；距旧单免费取消截止至少留 1 仿真小时。退款未到账期间不重复换订。": "; keep at least 1 simulation hour before old order free cancellation deadline. No repeated rebooking during refund pending period.",
  "停止持续监控": "Stop continuous monitoring",
  "启用订后监控": "Enable post-booking monitoring",
  "推进 30 仿真分钟": "Advance 30 simulation minutes",
  "仍计入占款": "Still counted as funds held",
  "退款尚未到账": "Refund not yet received",
  "当前状态": "Current status",
  "查看这一步的决策依据": "View decision basis for this step",
  "条近期记录": "recent records",
  "打开完整记录 →": "Open full record →",
  "· 事件 #": "· Event #",
  "· 当时授权见完整记录": "· Authorization at that time see full record",
  "打开当时网页截图 ↗": "Open webpage screenshot at that time ↗",
  "尚无观察记录。": "No observation records yet.",
  "当前授权无解，看看这些条件组合": "Current authorization unsolvable, check these condition combinations",
  "可选择提高预算，或调整已列出的软条件；必须设施、评论底线及取消权限仍保留。修改并重新确认授权后才可购买。": "Can increase budget or adjust listed soft conditions; must-have facilities, review bottom line and cancellation rights retained. Purchase only after modifying and reconfirming authorization.",
  "调整预算": "Adjust budget",
  "调整软条件": "Adjust soft conditions",
  "· 含税总价": "· Total price with tax",
  "查看酒店依据 ↗": "View hotel basis ↗",
  "预订成功": "Booking successful",
  "已取消": "Cancelled",
  "等待退款": "Waiting for refund",
  "退款到账": "Refund received",
  "取消失败 · 待核验": "Cancellation failed · Pending verification",
  "订单与资金状态": "Order and fund status",
  "笔订单": "orders",
  "实付含税": "Actual payment with tax",
  "订单编号": "Order number",
  "授权版本": "Authorization version",
  "退款金额": "Refund Amount",
  "换订来源": "Rebooking Source",
  "去平台核验订单 ↗": "Verify Order on Platform ↗",
  "尚未产生订单": "No Order Generated Yet",
  "完成授权后，智能体找到合格酒店即可预订。每笔扣款与退款会分别记录。": "After completing authorization, the agent can book once a qualified hotel is found. Each deduction and refund will be recorded separately.",
  "住得近一点，旅途轻松一点。": "Stay closer, travel easier.",
  "在杭州发现适合你的住宿": "Find Accommodation That Suits You in Hangzhou",
  "好住，也要好价。": "Great Stay, Great Price Too.",
  "三平台仿真市场 · 今日酒店报价": "3-Platform Simulation Market · Today's Hotel Quotes",
  "让住宿，成为目的地的一部分。": "Make Your Stay Part of the Destination.",
  "泊客精选 · 杭州城市旅居": "Park Guest Selection · Hangzhou Urban Stay",
  "取消申请已处理": "Cancellation Request Processed",
  "预订成功，测试资金已扣款": "Booking Successful, Test Funds Deducted",
  "交易被规则阻止": "Transaction Blocked by Rules",
  "请查看订单状态与资金流水。": "Please Check Order Status and Fund Flow.",
  "规则代码：": "Rule Code:",
  "酒店住宿": "Hotel Accommodation",
  "我的订单": "My Orders",
  "智能体控制台 ↗": "Agent Console ↗",
  "仿真时间 ·": "Simulation Time ·",
  "运行": "Run",
  "旅居氛围示意图": "Stay Atmosphere Diagram",
  "家测试酒店": "Test Hotels",
  "价格随仿真时钟变化": "Prices Change with Simulation Clock",
  "酒店名称": "Hotel Name",
  "搜索酒店 / 区域": "Search Hotels / Areas",
  "最低评分": "Minimum Rating",
  "不限 · 10分制": "No Limit · 10-Point Scale",
  "不限 · 5分制": "No Limit · 5-Point Scale",
  "最高总价": "Maximum Total Price",
  "不限 · 元": "No Limit · CNY",
  "搜索酒店": "Search Hotels",
  "报价含税 · 人民币": "Tax-Inclusive Quotes · CNY",
  "搜索结果": "Search Results",
  "杭州 · 酒店推荐": "Hangzhou · Hotel Recommendations",
  "家酒店": "Hotels",
  "按当前网页可见报价 ·": "Based on Visible Quotes on Current Page ·",
  "重新搜索": "Search Again",
  "没有满足筛选条件的酒店": "No Hotels Meet the Filter Criteria",
  "放宽评分或预算条件，重新搜索。智能体只有在授权允许时才会降级。": "Loosen rating or budget criteria and search again. The agent will only downgrade if authorized.",
  "重新读取酒店": "Reload Hotels",
  "杭州酒店": "Hangzhou Hotels",
  "确认预订": "Confirm Booking",
  "条评价": "Reviews",
  "氛围示意图 · 非真实酒店实拍": "Atmosphere Diagram · Not Real Hotel Photos",
  "酒店与你的目的地": "Hotels and Your Destination",
  "步行到目的地": "Walk to Destination",
  "地铁到目的地": "Take Subway to Destination",
  "分钟 ·": "Minutes ·",
  "直达": "Direct",
  "需换乘": "Transfer Required",
  "开业年份": "Opening Year",
  "信息未知": "Information Unknown",
  "翻新年份": "Renovation Year",
  "暂无翻新记录": "No Renovation Records Yet",
  "住客评论": "Guest Reviews",
  "条种子评论": "Seed Reviews",
  "以下评论为仿真样本，展示不同住客的具体体验。平台评分与展示样本数量分别保留。": "The following reviews are simulation samples showing specific experiences of different guests. Platform ratings and the number of displayed samples are retained separately.",
  "暂无评论样本": "No Review Samples Yet",
  "样本不足，无法据此判断问题出现频率。": "Insufficient samples to judge the frequency of issues based on this.",
  "有窗": "With Window",
  "无窗": "No Window",
  "窗型未知": "Window Type Unknown",
  "含早餐": "Breakfast Included",
  "不含早餐": "Breakfast Not Included",
  "住宿含税总价": "Total Accommodation Price (Tax Included)",
  "房费": "Room Rate",
  "税费": "Taxes",
  "当前已售罄": "Currently Sold Out",
  "选择房型并预订": "Select Room Type and Book",
  "查看售罄房型": "View Sold Out Room Types",
  "报价观察于": "Quote Observed at",
  "。结算时将再次核验价格与库存。": ". Price and inventory will be verified again at settlement.",
  "测试交易": "Test Transaction",
  "确认你的住宿预订": "Confirm Your Accommodation Booking",
  "交易守卫将独立审核有效授权、含税预算、测试余额与取消条款。": "The transaction guard will independently review valid authorization, tax-inclusive budget, test balance and cancellation terms.",
  "酒店氛围示意图": "Hotel Atmosphere Diagram",
  "入住安排": "Check-in Arrangements",
  "人 ·": "Guests ·",
  "间房": "Rooms",
  "取消政策": "Cancellation Policy",
  "此房价不可取消。支付成功后不支持退款，智能体停止继续换订。": "This rate is non-cancellable. No refund is supported after successful payment, and the agent will stop further rebooking.",
  "指定时间前取消可全额退款；超过时间后不可退款。退款处理有延迟，到账前资金仍占用。": "Full refund is available for cancellations made before the specified time; no refund after the deadline. Refund processing has a delay, and funds remain occupied until they arrive.",
  "授权与资金核验": "Authorization and Fund Verification",
  "当前授权": "Current Authorization",
  "已撤销": "Revoked",
  "未确认": "Unconfirmed",
  "测试可用余额": "Available Test Balance",
  "临时占款上限": "Temporary Occupancy Limit",
  "不可取消房授权": "Non-Cancellable Room Authorization",
  "已允许": "Allowed",
  "未允许": "Not Allowed",
  "授权额度不会产生钱包余额；超出任何一条边界，交易都会被实际阻止。": "The authorized limit does not generate wallet balance; any transaction exceeding any boundary will be actually blocked.",
  "付款明细": "Payment Details",
  "住宿房费": "Accommodation Room Rate",
  "测试人民币 · 不涉及真实扣款": "Test CNY · No Real Deduction Involved",
  "确认支付并预订": "Confirm Payment and Book",
  "查看我的订单": "View My Orders",
  "价格可能动态变化。提交时服务端复核报价、库存与授权版本。": "Prices may change dynamically. The server will review quotes, inventory and authorization version upon submission.",
  "重新核验当前报价 ↻": "Re-verify Current Quotes ↻",
  "· 测试订单与退款状态": "· Test Order and Refund Status",
  "继续浏览酒店": "Continue Browsing Hotels",
  "订单": "Orders",
  "· 创建": "· Create",
  "退款": "Refund",
  "待处理": "Pending",
  " · 请以当前状态为准": " · Please refer to the current status",
  "取消订单": "Cancel Order",
  "你在这个平台还没有订单": "You have no orders on this platform yet",
  "前往酒店页面浏览，或在控制台授权智能体自主比较。": "Go to the hotel page to browse, or authorize the agent to compare independently in the console.",
  "· 独立仿真商户": "· Independent Simulation Merchant",
  "所有房源、评价、价格与订单均为测试数据": "All listings, reviews, prices, and orders are test data",
  "返回 StayPilot 控制台 ↗": "Return to StayPilot Console ↗",
  "氛围示意图": "Ambience Diagram",
  "· 步行到目的地": "· Walk to Destination",
  "开业年份未知": "Opening Year Unknown",
  "地铁直达": "Direct Subway Access",
  "地铁换乘": "Subway Transfer",
  "间可订": "rooms available",
  "含税总价 · 税费": "Total Price Including Tax · Taxes",
  "查看酒店": "View Hotel",
  "浏览市场后展示已观察报价走势": "Display observed price trends after browsing the market",
  "已观察最低报价": "Observed Lowest Price",
  "非未来预测": "Not a Future Prediction",
  "已观察的三平台最低含税报价走势": "Observed lowest tax-inclusive price trends across three platforms",
  "仅使用智能体已观察的当前网页报价": "Only use current web prices observed by the agent",
  "西湖": "West Lake",
  "真实酒店数据 · 仅查询与核验，不会下单或扣款": "Real Hotel Data · Query and verify only, no booking or charges",
  "找到酒店，再确认细节。": "Find a hotel, then confirm details.",
  "查看真实搜索价格，选择酒店后核对房型、取消政策和通勤。": "Check real search prices, then verify room type, cancellation policy, and commute after selecting a hotel.",
  "查询房型与取消政策": "Check Room Type and Cancellation Policy",
  "返回体验首页": "Return to Experience Homepage",
  "查询流程": "Query Process",
  "填写行程": "Fill in Itinerary",
  "核对详情与通勤": "Verify Details and Commute",
  "你的行程": "Your Itinerary",
  "附近地点选填，可以填写景点、商圈或会议地址。": "Nearby location is optional; you can enter attractions, business districts, or meeting addresses.",
  "飞猪真实搜索": "Fliggy Real Search",
  "目的地城市": "Destination City",
  "附近地点（选填）": "Nearby Location (Optional)",
  "如：西湖": "e.g., West Lake",
  "正在查找酒店…": "Searching for hotels...",
  "查询未完成：": "Query incomplete:",
  "正在获取飞猪酒店数据，请稍候。": "Fetching Fliggy hotel data, please wait.",
  "先从一段行程开始": "Start with an itinerary first",
  "点击「查找酒店」查看候选，再打开平台详情或核对酒店到目的地的通勤。": "Click 'Search Hotels' to view candidates, then open platform details or check commute from hotel to destination.",
  "酒店查询结果": "Hotel Search Results",
  "找到": "Found",
  "· 查询于": "· Queried at",
  "（上海时间）": "(Shanghai Time)",
  "搜索价，需核对房型": "Search price, room type needs verification",
  "行程已修改。以下是上一次查询结果，请重新查找酒店。": "Itinerary modified. Below are the previous search results, please search for hotels again.",
  "暂未找到酒店": "No hotels found yet",
  "试试更换附近地点，或调整入住日期后再次查询。": "Try changing the nearby location or adjusting the check-in date and search again.",
  "飞猪真实酒店": "Fliggy Real Hotels",
  "平台暂未提供地址": "Platform has not provided address yet",
  "平台搜索价": "Platform Search Price",
  "具体房型、含税总价与取消条款，请在平台详情页确认。": "Please confirm specific room type, total price including tax, and cancellation terms on the platform details page.",
  "查看飞猪详情 ↗": "View Fliggy Details ↗",
  "查看通勤路线": "View Commute Route",
  "评分、装修及待核验信息": "Rating, Renovation, and Pending Verification Information",
  "平台评分原值：": "Platform Rating Original Value:",
  "未提供": "Not Provided",
  "，评分尺度待核验。装修时间：": ", rating scale pending verification. Renovation time:",
  "，不能代替开业时间。": ", cannot replace opening time.",
  "尚待确认：": "Pending confirmation:",
  "请以平台详情为准": "Please refer to platform details",
  "平台酒店编号：": "Platform Hotel ID:",
  "平台提示：": "Platform Notice:",
  "查询说明与预订限制": "Query Instructions and Booking Restrictions",
  "搜索价格尚未绑定具体房型、人数、餐食、税费和取消政策。搜索地点与排序条件也需要在详情页再次确认；评分为 0 或缺失时，不作为酒店质量判断。": "Search price is not yet bound to specific room type, number of guests, meals, taxes, and cancellation policy. Search location and sorting conditions also need to be reconfirmed on the details page; when rating is 0 or missing, it is not used as a basis for hotel quality judgment.",
  "当前不会自动预订。真实结果不会进入体验钱包或测试订单，打开平台详情也不会创建订单。接口密钥保存在服务端。": "No automatic booking currently. Real results will not enter the experience wallet or test orders, and opening platform details will not create orders. API keys are stored on the server.",
  "未满足当前授权，不能自动预订。下方保留具体冲突和网页依据。": "Current authorization not met, cannot book automatically. Specific conflicts and web basis are retained below.",
  "本轮仍在读取网页，目前只掌握部分证据。最终首选以完整排序为准。": "This round is still reading web pages, currently only partial evidence is available. The final preferred choice is based on the complete ranking.",
  "符合当前授权，等待本轮完成比较。": "Meets current authorization, waiting for this round to complete comparison.",
  "这里仅比较平台 A，其他平台尚需核验。": "Only Platform A is compared here, other platforms still need verification.",
  "酒店排序不代表预订成功，订单以商户确认为准。": "Hotel ranking does not mean booking is successful, orders are subject to merchant confirmation.",
  "作为备选：比首选需要放宽更多住宿偏好。": "As an alternative: requires relaxing more accommodation preferences than the preferred choice.",
  "作为备选：同档位下，已读评论中你在意的问题风险比首选更高。": "As an alternative: at the same level, the risk of issues you care about in read reviews is higher than the preferred choice.",
  "作为备选：档位和评论风险相同，但含税总价高于首选。": "As an alternative: same level and review risk, but total price including tax is higher than the preferred choice.",
  "作为备选：条件、风险和价格相同，但步行时间长于首选。": "As an alternative: same conditions, risk, and price, but walking time is longer than the preferred choice.",
  "与首选条件相当，作为本轮备选保留。": "Comparable to the preferred choice conditions, retained as an alternative for this round.",
  "当前报价未通过授权规则，不能自动预订。": "Current quote did not pass authorization rules, cannot book automatically.",
  "完整满足你的首选条件": "Fully meets your preferred conditions",
  "使用你已授权的放宽条件": "Using your authorized relaxed conditions",
  "已读评论未触发个人风险": "Read reviews did not trigger personal risk",
  "已读评论中有你在意的问题": "Read reviews contain issues you care about",
  "平台 A 暂定首选": "Platform A Tentatively Preferred",
  "当前暂定首选": "Currently Tentatively Preferred",
  "本轮首选": "Preferred for This Round",
  "已观察酒店比较": "Observed Hotel Comparison",
  "搜索酒店、位置或设施": "Search hotels, locations, or facilities",
  "筛选酒店": "Filter Hotels",
  "全部": "All",
  "符合偏好": "Matches Preferences",
  "已排除": "Excluded",
  "显示": "Show",
  "家酒店 · 符合偏好包含你已授权的放宽条件，优先展示可预订方案。": "hotels · Matching preferences includes your authorized relaxed conditions, prioritizing display of bookable options.",
  "· 全程含税总价": "· Total Price Including Tax for Entire Stay",
  "· 步行": "· Walking",
  "本轮核验要求": "Current verification requirements",
  "问题出现即排除": "Exclude if issues found",
  "“重要”与“不可接受”分别控制。评论样本指标不是全体住客的问题概率。": "Importance and Unacceptable are controlled separately. Review sample metrics are not the problem probability for all guests.",
  "回放使用 10 月 4 日的既有观察；实时模式重新查询报价与地图，评论仅合并已采集且身份匹配的历史证据。最多检查 12 家位置、3 家 RollingGo 房型，未覆盖全市场。": "Playback uses existing observations from October 4; real-time mode re-queries prices and maps, reviews only merge collected historical evidence with matching identities. Checks up to 12 locations and 3 RollingGo room types, not covering the full market.",
  "正在执行：": "Executing:",
  "状态：": "Status:",
  "每 30 真实分钟重新运行检索、房型、地图与规则评估，到截止时间停止。评论仍是已采集的历史证据；不自动换订。": "Re-runs search, room types, maps, and rule evaluation every 30 real minutes, stopping at the deadline. Reviews remain collected historical evidence; no automatic rebooking.",
  "后台和电脑需保持运行；重启后不自动恢复。启动时锁定当前表单条件，之后修改表单不改变已有监控。": "Background and computer must remain running; does not auto-resume after restart. Locks current form conditions at startup; modifying forms later does not change existing monitoring.",
  "持续核验中": "Continuous verification in progress",
  "· 已完成": "· Completed",
  "轮": "Round",
  " · 下次 ": " · Next ",
  "实时报价与路线＋历史评论": "Real-time prices & routes + historical reviews",
  "历史证据回放": "Historical evidence playback",
  "成人 · 本轮预算 ¥": "Adults · Current round budget ¥",
  "完成于": "Completed at",
  "· 证据基准": "· Evidence baseline",
  "· 真实交易关闭": "· Real transaction closed",
  "顺序为待核验优先级，全部候选均不可自动购买。按硬条件、通勤档位、个人样本指标、展示价格、通勤时长排序；未知评论不视为零风险。": "Order is pending verification priority; all candidates cannot be auto-purchased. Sorted by hard conditions, commute tier, personal sample metrics, displayed price, commute duration; unknown reviews are not considered zero risk.",
  "· 报价观察": "· Price observation",
  " 房型展示价": " Room type display price",
  "未取得合适房型报价": "No suitable room type price obtained",
  "通勤不符合或未知": "Commute does not match or unknown",
  "窗型：": "Window type:",
  "内窗／暗窗": "Inner window / dark window",
  "文字明确外窗": "Text explicitly states outer window",
  "API 有窗，但类型未明": "API indicates window but type unclear",
  "免费取消截止 ": "Free cancellation deadline ",
  "取消期限未确认": "Cancellation deadline unconfirmed",
  "查看个人评论指标与来源": "View personal review metrics and sources",
  "样本不足，风险未知": "Insufficient sample, unknown risk",
  "加权样本指标 ": "Weighted sample metrics ",
  "；不是总体问题概率": "; not overall problem probability",
  "× 重要度": "× Importance",
  "采集于": "Collected from",
  "打开平台原评论": "Open original platform review",
  "正面 ·": "Positive ·",
  "日期待绑定": "Date pending binding",
  "需要补齐的证据（": "Evidence needed to complete (",
  "打开酒店页面 ↗": "Open hotel page ↗",
  "其他证据仍需核验": "Other evidence still needs verification",
  "以上建议不改变本轮预算、硬底线或授权，不保证对应报价可成交。": "Above suggestions do not change current round budget, hard bottom line, or authorization; no guarantee that corresponding prices can be transacted.",
  "Jev：基于本轮合并证据的下一步建议": "Jev: Next step suggestions based on current round merged evidence",
  "· 不参与授权或购买决策": "· Does not participate in authorization or purchase decisions",
  "建议核验对象：": "Suggested verification targets:",
  "· 置信度": "· Confidence",
  "下一步：": "Next step:",
  "模型读取房型、路线、评论与缺口摘要，结果绑定本轮证据哈希；概率与置信度不等于事实正确或交易权限。": "Model reads room types, routes, reviews, and gap summaries; results bound to current round evidence hash. Probability and confidence do not equal factual correctness or transaction permissions.",
  "证据版本与哈希链": "Evidence version and hash chain",
  "导出包含每条记录的前序哈希与当前哈希，可重算验证。哈希不证明原始来源真实性。": "Export includes previous hash and current hash for each record, can be recalculated for verification. Hash does not prove original source authenticity.",
  "离目的地稍远一点": "Slightly farther from destination",
  "步行范围外，接受地铁直达": "Outside walking range, accept direct subway",
  "接受开业较早的酒店": "Accept hotels opened earlier",
  "放宽所选开业或翻新年份": "Relax selected opening or renovation year",
  "接受评分稍低的酒店": "Accept hotels with slightly lower ratings",
  "先看差评原因，仍须达到最低评分": "Check negative review reasons first, still must meet minimum rating",
  "接受无窗房间": "Accept windowless rooms",
  "仅在窗型要求允许时生效": "Only effective when window type requirements allow",
  "请填写时间": "Please fill in time",
  "偏好与授权已确认，可以开始查找并预订酒店": "Preferences and authorization confirmed, can start searching and booking hotels",
  "行程与偏好草稿已保存": "Itinerary and preference draft saved",
  "已填入下方，请核对后确认。": "Filled in below, please review and confirm.",
  "当前授权有效": "Current authorization valid",
  "修改后需要重新确认；撤销授权会保留已有住宿。": "Need to reconfirm after modification; revoking authorization will retain existing accommodation.",
  "授权已撤销；已有住宿保留": "Authorization revoked; existing accommodation retained",
  "撤销授权": "Revoke authorization",
  "用一句话填写偏好": "Fill in preferences in one sentence",
  "可选 · 帮你整理成下方设置": "Optional · Help organize into settings below",
  "描述你的住宿需求": "Describe your accommodation needs",
  "例如：预算500元，步行15分钟内，隔音不能差；预算不足时先放宽开业年份。": "Example: Budget 500 yuan, within 15 minutes walk, soundproofing must be good; relax opening year first if budget is insufficient.",
  "提取结果是草稿，请核对后再确认授权。": "Extraction result is a draft, please review before confirming authorization.",
  "正在整理…": "Organizing...",
  "帮我填写": "Help me fill in",
  "景点、办公地点或具体地址": "Attractions, office locations, or specific addresses",
  "临时占款上限（元）": "Temporary fund occupation limit (yuan)",
  "换订时新旧订单和未到账退款会同时占款。此上限与住宿预算、钱包余额分别审核。": "When rebooking, old and new orders and unarrived refunds will occupy funds simultaneously. This limit is reviewed separately from accommodation budget and wallet balance.",
  "什么样的酒店更适合你？": "What kind of hotel suits you better?",
  "先设置理想条件，预算不足时再按你的顺序放宽。": "Set ideal conditions first, then relax in your order if budget is insufficient.",
  "你的入住偏好": "Your check-in preferences",
  "期望步行上限（分钟）": "Expected walking limit (minutes)",
  "接受地铁上限（分钟）": "Acceptable subway limit (minutes)",
  "期望评分（5分制）": "Expected rating (5-point scale)",
  "最低可接受评分": "Minimum acceptable rating",
  "酒店新旧按什么看？": "How to judge hotel age?",
  "开业或翻新年份": "Opening or renovation year",
  "期望年份不早于": "Expected year not earlier than",
  "房间窗型": "Room window type",
  "必须有窗，不能放宽": "Must have window, cannot be relaxed",
  "有窗优先，允许按顺序放宽": "Window preferred, relaxation allowed in order",
  "有窗、无窗都可以": "Window or no window both acceptable",
  "预算不够，先放宽哪一项？": "If budget is insufficient, which item to relax first?",
  "从上往下尝试。调整顺序，让智能体按你的取舍寻找酒店。": "Try from top to bottom. Adjust order to let the agent find hotels according to your trade-offs.",
  "上移": "Move up",
  "下移": "Move down",
  "＋ 允许最后尝试无窗房": "+ Allow trying windowless rooms last",
  "移除无窗房的放宽许可": "Remove relaxation permission for windowless rooms",
  "必须有窗、必须设施和不能接受的评论问题始终是底线。": "Must have window, must-have facilities, and unacceptable review issues are always bottom lines.",
  "这些入住问题，你有多在意？": "How much do you care about these check-in issues?",
  "勾选“不能接受”会直接排除。其他问题可设重要程度：0 不在意，5 非常在意。": "Checking Unacceptable will directly exclude. Other issues can set importance level: 0 don't care, 5 very important.",
  "不能接受": "Unacceptable",
  "地铁需换乘": "Subway transfer required",
  "窗型未确认": "Window type unconfirmed",
  "平台评分": "Platform rating",
  "查看酒店网页 ↗": "View hotel website ↗",
  "比较": "Compare",
  "个平台的报价": "platform quotes",
  "含税价格与取消政策": "Price including tax and cancellation policy",
  "平台 / 评分与取消政策": "Platform / Rating and cancellation policy",
  "全程含税总价": "Total price including tax for entire stay",
  "条评价 ·": "reviews ·",
  "此报价不符合授权：": "This quote does not meet authorization:",
  "观察": "Monitor",
  "核验网页 ↗": "Verify webpage ↗",
  "为什么这样推荐": "Why this recommendation",
  "查看排除原因": "View exclusion reason",
  "排序与筛选依据": "Sorting and filtering criteria",
  "偏好条件": "Preference criteria",
  "完整满足": "Fully met",
  "个人评论风险 · 越低越好": "Individual review risk · Lower is better",
  "开业 / 翻新年份": "Opening / Renovation year",
  "未知": "Unknown",
  "无": "None",
  "已见设施：": "Seen amenities:",
  "暂无已确认设施": "No confirmed amenities yet",
  "匹配参考分": "Matching reference score",
  "/ 100 · 计算方式": "/ 100 · Calculation method",
  "参考分帮助理解取舍，不改变实际排序：授权规则 → 放宽档位 → 评论风险 → 含税总价 → 步行时间。": "Reference score helps understand trade-offs, does not change actual ranking: Authorization rules → Relaxed tier → Review risk → Total price including tax → Walking time.",
  "查看评论原文 ·": "View original review ·",
  "条": "items",
  "保留正反意见与来源": "Retain both positive and negative opinions and sources",
  "以下是实际已读样本，不能代表全部住客体验。": "Below are actual samples read, cannot represent all guest experiences.",
  "来源：": "Source:",
  "没有找到匹配的酒店": "No matching hotels found",
  "此分类暂时没有酒店": "No hotels in this category temporarily",
  "换个关键词或查看全部酒店。": "Try different keywords or view all hotels.",
  "显示全部酒店": "Show all hotels",
  "订后比较": "Post-booking comparison",
  "为你精选": "Selected for you",
  "当前住宿与备选酒店": "Current accommodation and alternative hotels",
  "先看首选，再看备选": "View primary choice first, then alternatives",
  "正在核验其他平台，以下为当前已读范围内的暂定结果。": "Verifying other platforms, below are tentative results within current read scope.",
  "按你的授权条件排序，每家酒店保留一份优选报价。": "Sorted by your authorization criteria, each hotel retains one preferred quote.",
  "家": "hotels",
  "备选": "Alternative",
  "符合授权": "Meets authorization",
  "当前已订": "Currently booked",
  "暂定首选": "Tentative primary choice",
  "全程含税 ·": "All-inclusive tax ·",
  "分": "points",
  "偏好或评论风险比当前住宿差，不能换订。": "Preferences or review risk worse than current accommodation, cannot switch booking.",
  "换订前仍须核验节省金额、取消期限与可用余额。": "Before switching booking, still need to verify savings amount, cancellation deadline and available balance.",
  "正在核验酒店": "Verifying hotel",
  "暂时没有符合授权的酒店": "Temporarily no hotels meeting authorization criteria",
  "实际读过酒店详情和评论后，符合条件的酒店会显示在这里。": "After actually reading hotel details and reviews, qualified hotels will be displayed here.",
  "可查看排除原因，或调整预算与可放宽的条件。": "Can view exclusion reasons, or adjust budget and relaxable conditions.",
  "当前有": "Currently have",
  "合格备选": "Qualified alternatives",
  "合格酒店": "Qualified hotels",
  "，没有用不符合授权的酒店补足数量。": ", did not use hotels not meeting authorization to fill quota.",
  "监控每 30 仿真分钟复查当前酒店和备选，同时发现新候选；只在授权和免费取消期限内换订。": "Monitor and review current hotel and alternatives every 30 simulated minutes, while discovering new candidates; only switch booking within authorization and free cancellation period.",
  "首选与备选均来自已读网页；实际入住安排以商户确认订单为准。": "Primary choice and alternatives all from read webpages; actual check-in arrangements subject to merchant confirmed orders.",
  "优先核验可取消、有窗的房型；我浅眠，需要卫生与隔音评论证据。这里只安排查证顺序，不改变预算或购买授权。": "Priority verification of cancellable, windowed room types; I am a light sleeper, need hygiene and soundproofing review evidence. Here only arranges verification order, does not change budget or purchase authorization.",
  "未取得新判断": "No new judgment obtained",
  "需要帮助决定先看哪家？": "Need help deciding which to view first?",
  "AI 核验建议": "AI verification suggestion",
  "告诉我们，你最在意什么": "Tell us what you care about most",
  "根据已经查询到的酒店，建议优先补查的候选和信息。建议不会改变预算、个人底线或预订权限。": "Based on already queried hotels, suggests candidates and information to prioritize for supplementary verification. Suggestions will not change budget, personal bottom line or booking permissions.",
  "入住关注点": "Stay priorities",
  "如：希望可免费取消，浅眠，重点关注隔音与卫生。": "E.g.: Hope for free cancellation, light sleeper, focus on soundproofing and hygiene.",
  "正在整理建议…": "Organizing suggestions...",
  "获取核验建议": "Get verification suggestion",
  "先查找酒店，再根据真实候选获取建议。": "Search for hotels first, then get suggestions based on real candidates.",
  "建议服务尚未配置。你仍可以直接选择酒店，核对房型和通勤。": "Suggestion service not yet configured. You can still directly select hotels, check room types and commute.",
  "查询信息或关注点已变化，请重新获取建议。": "Query information or focus points have changed, please re-acquire suggestions.",
  "建议先看": "Suggest viewing first",
  "优先补查这家酒店的房型与取消政策。": "Priority supplementary verification of this hotel's room types and cancellation policy.",
  "现有信息不足以优先选择候选，可以继续补充房型、评论或通勤信息。": "Current information insufficient to prioritize candidates, can continue to supplement room type, review or commute information.",
  "查看这家酒店的房型": "View this hotel's room types",
  "当前酒店还需确认": "Current hotel still needs confirmation",
  "这项建议对应当前已选酒店，可能与左侧候选不同。": "This suggestion corresponds to currently selected hotel, may differ from left side candidates.",
  "建议生成于": "Suggestion generated at",
  "（香港时间）。仅安排查证顺序，未执行动作或创建订单。": "(Hong Kong Time). Only arranges verification order, did not execute actions or create orders.",
  "查看判断依据与可信度": "View judgment basis and credibility",
  "所用搜索查询于": "Search query used at",
  "。候选优先级与当前酒店的下一步分别判断，概率表示模型倾向，置信度不是正确率或购买许可。": ". Candidate priority and next steps for current hotel judged separately, probability indicates model tendency, confidence is not accuracy rate or purchase permission.",
  "候选建议 · 置信度": "Candidate suggestion · Confidence",
  "的模型概率": "model probability",
  "下一步建议 · 置信度": "Next step suggestion · Confidence",
  "技术诊断与原始输入": "Technical diagnosis and original input",
  "TypeSafe Jev · 模型": "TypeSafe Jev · Model",
  "· 耗时": "· Time taken",
  "ms · 输入": "ms · Input",
  "/ 输出": "/ Output",
  "核验未完成": "Verification incomplete",
  "北京": "Beijing",
  "雍和宫": "Yonghe Temple",
  "StayPilot · 控制台": "StayPilot · Console",
  "飞猪查询": "Fliggy search",
  "房型详情": "Room type details",
  "首次测试报告": "First test report",
  "已配置凭证仅表示本机有配置，能否使用以实际查询结果为准。": "Configured credentials only indicate local configuration; actual usability depends on query results.",
  "已配置": "Configured",
  "未配置": "Not configured",
  "币种未知 ": "Currency unknown ",
  "可核验免费取消": "Verifiable free cancellation",
  "不可退款": "Non-refundable",
  "单份早餐": "Single breakfast",
  "双份早餐": "Double breakfast",
  "查询未完成": "Query incomplete",
  "真实酒店与房型数据 · 仅查询与核验，不会下单或扣款": "Real hotel and room data · Query and verification only, no booking or charges",
  "RollingGo 酒店与房型": "RollingGo Hotels & Rooms",
  "看清房型，也看清取消条件。": "Check room types and cancellation terms.",
  "先找到酒店，再查看对应行程的房型报价、餐食和取消条款。": "Find the hotel first, then check room rates, meals, and cancellation terms for your itinerary.",
  "选择酒店": "Select hotel",
  "核对房型与条款": "Verify room types and terms",
  "当前支持 1 间房、无儿童入住；成人数可调整。": "Currently supports 1 room, no children; adult count adjustable.",
  "真实房型查询": "Real room type search",
  "成人数": "Number of adults",
  "正在获取酒店或房型数据，请稍候。": "Fetching hotel or room data, please wait.",
  "从酒店开始，逐项确认": "Start with the hotel, confirm each item",
  "查找酒店后，点击「查看房型与取消政策」，确认价格对应的床型、早餐和退款条件。": "After finding the hotel, click 'View room types and cancellation policy' to confirm bed type, breakfast, and refund conditions for the price.",
  "成人 / 1 间 · 查询于": "Adults / 1 room · Searched on",
  "搜索价按每晚展示": "Search prices shown per night",
  "行程已修改。以下仍是上一次查询结果，请重新查找酒店。": "Itinerary modified. Below is the previous search result, please search for hotels again.",
  "房型筛选": "Room type filter",
  "全部取消政策": "All cancellation policies",
  "全部餐食": "All meals",
  "早餐": "Breakfast",
  "选择筛选条件后，点击酒店的「查看房型与取消政策」应用筛选。": "After selecting filters, click the hotel's 'View room types and cancellation policy' to apply.",
  "试试调整附近地点或日期后再次查询。": "Try adjusting nearby locations or dates and search again.",
  "RollingGo 真实酒店": "RollingGo Real Hotels",
  "酒店星级": "Hotel star rating",
  "/ 晚 · 搜索展示价": "/ night · Search display price",
  "查看房型与取消政策": "View room types and cancellation policy",
  "平台详情 ↗": "Platform details ↗",
  "星级表示酒店等级；住客评分尚未提供。价格需结合具体房型确认。": "Star rating indicates hotel class; guest scores not yet available. Prices need to be confirmed with specific room types.",
  "房型与取消政策": "Room types and cancellation policy",
  "含税总价待确认": "Total price with tax pending confirmation",
  "本次筛选：": "Current filters:",
  "。报价与库存需在预订时再次确认。": ". Rates and availability need to be reconfirmed at booking.",
  "本次没有匹配的房型": "No matching room types found",
  "可调整上方房型筛选后重查。这不代表酒店所有房型都已售罄。": "Adjust the room type filters above and search again. This does not mean all room types at the hotel are sold out.",
  "可免费取消": "Free cancellation available",
  "取消条款待确认": "Cancellation terms pending confirmation",
  "床型未提供": "Bed type not provided",
  "窗型未提供": "Window type not provided",
  "· 最多": "· Up to",
  "人": "people",
  " 平方米": " sqm",
  "餐食未提供": "Meals not provided",
  "· 早餐": "· Breakfast",
  "份": "servings",
  "暂算": "Estimated",
  "晚": "nights",
  "平均": "Average",
  "/ 晚，暂算价格尚未确认税费及到店费用。": "/ night, estimated price does not include taxes and on-site fees.",
  "免费取消截止：": "Free cancellation deadline:",
  "（UTC+8，已映射城市的酒店当地时间）": "(UTC+8, mapped to hotel local time)",
  "此房型不可退款，请确认是否符合你的入住计划。": "This room type is non-refundable, please confirm if it fits your stay plans.",
  "取消政策或酒店时区尚未完整确认。": "Cancellation policy or hotel timezone not fully confirmed.",
  "查看取消原文与待确认事项": "View original cancellation text and pending items",
  "平台取消原文：": "Platform cancellation original text:",
  "可售状态尚未提供": "Availability status not provided",
  "需要商户二次确认": "Requires merchant reconfirmation",
  "接口未标记需二次确认，仍需在预订前复核库存": "Interface not marked for reconfirmation, inventory still needs verification before booking",
  "房间面积尚未提供。": "Room area not provided.",
  "查看本次报价的核验说明": "View verification notes for this quote",
  "。真实订单与支付未启用。": ". Real orders and payments not enabled.",
  "连接状态与查询说明": "Connection status and query description",
  "已验证连接": "Connection verified",
  "尚未验证连接": "Connection not yet verified",
  "搜索价按每晚展示。房型平均价乘以晚数只是暂算住宿价格，税费、库存、评论与开业时间仍需确认。同名酒店或不同餐食、取消条款的报价，不能直接视为同一产品。": "Search prices shown per night. Room average price multiplied by nights is only an estimated accommodation cost; taxes, inventory, reviews, and opening dates still need confirmation. Quotes for hotels with the same name but different meals or cancellation terms cannot be directly considered the same product.",
  "检查数据源连接": "Check data source connection",
  "连接验证成功 ·": "Connection verified ·",
  "（上海时间）。仅开放搜索、详情与标签查询。": "(Shanghai time). Only search, details, and tag queries are available.",
  "查看接口与权限": "View interfaces and permissions",
  "服务：": "Service:",
  "未提供名称": "Name not provided",
  "只读已启用": "Read-only enabled",
  "禁止转发": "Forwarding prohibited",
  "配置凭证不等于连接已验证，可点击检查确认权限。": "Configured credentials do not mean connection is verified; click to check and confirm permissions.",
  "密钥保存在服务端，未开放自动下单。": "Keys are stored server-side, automatic ordering not enabled.",
  "历史查询记录": "Historical query records",
  "次搜索 ·": "searches ·",
  "次房型查询": "room type queries",
  "查询记录带有获取时间，刷新后会保留。历史报价不代表当前库存或价格。": "Query records include retrieval time and are preserved after refresh. Historical quotes do not represent current inventory or prices.",
  "不可取消": "Non-cancellable",
  "指定期限": "Specified period",
  "前免费取消": "Free cancellation before",
  "确定住宿附近的目的地、日期、人数和总预算。": "Determine nearby destinations, dates, number of people, and total budget for accommodation.",
  "取舍与授权": "Trade-offs and authorization",
  "提前排序可以放宽的条件，确认硬底线与购买权限。": "Sort conditions that can be relaxed in advance, confirm hard limits and purchase permissions.",
  "初筛与评论": "Initial screening and reviews",
  "从平台 A 建立意向清单，逐条核对评价证据。": "Create a shortlist from Platform A, verify review evidence one by one.",
  "三平台比价": "Compare prices across three platforms",
  "固定住宿条件，对照含税总价、取消期限和评分来源。": "Fix accommodation conditions, compare total price with tax, cancellation period, and rating sources.",
  "预订或阻断": "Book or block",
  "提交时再次核验授权、库存与资金，展示商户确认结果。": "Re-verify authorization, inventory, and funds at submission, display merchant confirmation results.",
  "订后监控": "Post-booking monitoring",
  "可取消时继续优化；退款到账前保留占款。": "Continue optimizing when cancellable; retain hold until refund is received.",
  "重要程度": "Importance level",
  "设施要求": "Facility requirements",
  " 项必须满足": "{count} items must be met",
  "洗衣、停车、健身等": "Laundry, parking, gym, etc.",
  "自助洗衣": "Self-service laundry",
  "免费停车": "Free parking",
  "健身房": "Gym",
  "行李寄存": "Luggage storage",
  "不要求": "Not required",
  "有的话更好": "Nice to have if available",
  "必须满足，不能放宽": "Must be met, no exceptions",
  "设施信息需要核验，信息未知时不能按满足处理。": "Facility information must be verified; if information is unknown, it cannot be counted as met.",
  "预订与价格监控设置": "Booking and price monitoring settings",
  "截止时间、取消权限、换订门槛": "Deadlines, cancellation rights, and rebooking thresholds",
  "首次预订截止（上海时间）": "First booking deadline (Shanghai Time)",
  "价格监控截止（上海时间）": "Price monitoring deadline (Shanghai Time)",
  "授权有效期（上海时间）": "Authorization validity period (Shanghai Time)",
  "换订至少净省（元）": "Minimum net savings for rebooking (CNY)",
  "同时至少省旧单金额的（%）": "And at least {X}% of the original booking amount saved",
  "允许自动购买不可取消房": "Allow automatic purchase of non-cancellable rooms",
  "预订后不能退款换订，默认关闭。": "No refund or rebooking after booking, disabled by default.",
  "换订需同时满足两个节省门槛，质量不能变差；先订新、再退旧，退款到账前不重复换订。": "Rebooking must meet both savings thresholds simultaneously, and room quality must not be reduced; book the new room first, then cancel the old one, and no repeated rebooking before the refund is received.",
  "温暖的酒店房间氛围示意": "Illustration of a warm hotel room atmosphere",
  "让每一次入住，都更合心意。": "Make every stay more to your liking.",
  "为你安排，按你取舍": "Arranged for you, based on your choices",
  "好住，也在预算之内。": "Great stay, within your budget.",
  "你的底线，优先满足": "Your bottom lines are prioritized",
  "卫生、隔音、有窗等要求，由你决定。": "Requirements such as cleanliness, sound insulation, and windows are up to you.",
  "跨平台比较，少一点纠结": "Cross-platform comparison, less hassle",
  "结合评论与总价，给你首选和备选。": "Combine reviews and total price to provide you with first and backup options.",
  "订好之后，继续留意价格": "After booking, keep monitoring prices",
  "在可取消的期限内，寻找更省的方案。": "Look for cheaper options within the cancellable period.",
  "本次住宿总预算": "Total budget for this stay",
  "当前为仿真体验，使用测试酒店与测试资金。": "This is a simulation experience, using test hotels and test funds.",
  "确认前，再看一眼": "Take another look before confirming",
  "取消要求": "Cancellation requirements",
  "允许不可取消房": "Allow non-cancellable rooms",
  "资金占用上限": "Fund occupation cap",
  "换订至少净省": "Minimum net savings for rebooking",
  "且": "And",
  "价格监控截止": "Price monitoring deadline",
  "未设置评论底线": "No review bottom line set",
  "我确认以上设置，授权智能体使用测试资金自动预订与换订。": "I confirm the above settings and authorize the agent to use test funds for automatic booking and rebooking.",
  "超出预算或底线时会停止购买；修改授权需要重新确认。": "Purchases will stop when the budget or bottom line is exceeded; modifying the authorization requires re-confirmation.",
  "已保存": "Saved",
  "正在保存…": "Saving...",
  "确认授权并保存": "Confirm authorization and save",
  "保存偏好草稿": "Save preference draft",
  "清洁": "Cleanliness",
  "设施": "Facilities",
  "夜间安全体验": "Nighttime safety experience",
  "真实交易已阻止：": "Real transaction blocked:",
  "暂时无法取得交易阻断结果": "Unable to obtain transaction blocking result temporarily",
  "定时查看价格变化": "Check price changes regularly",
  "监控中": "Monitoring",
  "每 30 分钟查询一次当前行程，到截止时间自动停止。": "Check the current itinerary every 30 minutes, and stop automatically when the deadline is reached.",
  "后台服务与电脑需保持运行；重启后需要重新开启。仅查询，不会自动预订。": "Background services and the computer need to stay running; you need to restart it after a reboot. Only queries are performed, no automatic booking.",
  "截止时间（上海时间）": "Deadline (Shanghai Time)",
  "正在更新…": "Updating...",
  "停止监控": "Stop monitoring",
  "开启价格监控": "Enable price monitoring",
  "正在监控当前行程": "Monitoring current itinerary",
  "开启后，会立即查询当前表单中的行程": "After enabling, it will immediately query the itinerary in the current form",
  " · 下次检查 ": "· Next check",
  "已有": "There are {count}",
  "次价格记录 · 最近查询": "price records · Recent query",
  "查看价格记录": "View price records",
  "本轮未返回酒店": "No hotel returned in this round",
  "查看运行与交易阻断记录": "View operation and transaction blocking records",
  "验证真实交易阻断": "Verify real transaction blocking",
  "了解评论中的入住体验": "Learn about the stay experience in reviews",
  "历史评论样本": "Historical review samples",
  "汉庭黄龙文三路 · 已核验评论样本": "Hanting Hotel (Huanglong Wensan Road) · Verified review samples",
  "2026 年 10 月 4 日浏览整理的历史证据，不是实时评论。仅对应这家酒店，其他酒店需分别查证。": "Historical evidence compiled and viewed on October 4, 2026, not real-time reviews. Only corresponds to this hotel; other hotels need to be verified separately.",
  "选择你的关注程度": "Select your level of concern",
  "浅眠，关注隔音、清洁与气味": "Light sleeper, concerned about sound insulation, cleanliness, and odor",
  "可接受隔音与空间代价，清洁优先": "Can accept trade-offs in sound insulation and space, with cleanliness as the priority",
  "与你的底线冲突：": "Conflicts with your bottom line:",
  "所选样本中未发现底线冲突": "No bottom line conflict found in the selected samples",
  "条样本提及": "{count} samples mention",
  "这里统计的是选出的 10 条差评，不代表全部": "This counts the 10 selected negative reviews, not all reviews",
  "条评论，也不能预测未来入住体验。部分旧评论可能重复。": "reviews, and cannot predict future stay experiences. Some old reviews may be duplicated.",
  "查看评论原文与正面反馈": "View original review text and positive feedback",
  "· 原文节选「": "· Excerpt from original text「",
  "正面反馈": "Positive feedback",
  "查看平台评分、房型观察与计算依据": "View platform ratings, room type observations, and calculation basis",
  "网页评分": "Web page rating",
  "，接口原值": ", original value from the interface",
  "；共": "; total",
  "条点评，差评标签": "reviews, negative review tags",
  "条。2022 年开业 / 装修。": ". Opened/renovated in 2022.",
  "样本风险分": "Sample risk score",
  "，仅用于展示不同关注权重下的结果，不构成购买授权。": ", only used to display results under different concern weights, does not constitute purchase authorization.",
  "· 权重": "· Weight",
  "历史房型：": "Historical room types:",
  "（网页显示价）。": "(Price shown on the web page).",
  "取消政策：": "Cancellation policy:",
  "含税总价、餐食及退款到账时间仍未确认，不能据此自动预订。": "Total price including tax, meals, and refund arrival time are not yet confirmed, cannot be booked automatically based on this.",
  "查看飞猪原评论与房型 ↗": "View original Fliggy reviews and room types ↗",
  "查看数据源连接状态": "View data source connection status",
  "正在核验": "Verifying",
  "截止无解": "Deadline passed, no solution",
  "有阻断记录": "Has blocking records",
  "冻结待处理": "Frozen, pending processing",
  "不可取消，已锁定": "Non-cancellable, locked",
  "优化期限或取消窗口已结束": "Optimization period or cancellation window has ended",
  "等待退款到账": "Waiting for refund to arrive",
  "可取消，监控未启用": "Cancellable, monitoring not enabled",
  "记录回放只支持原雍和宫案例的日期、地点和人数；修改行程请运行实时核验。": "Record playback only supports the original Yonghe Palace case's date, location, and number of people; to modify itinerary, please run real-time verification.",
  "号": "No.",
  "已取得路线不满足本轮通勤参数": "Obtained route does not meet this round's commuting parameters",
  "准确位置及通勤证据不足": "Insufficient accurate location and commuting evidence",
  "评论原文、日期、评分与样本不足": "Insufficient review text, date, rating, and samples",
  "未取得带问题标签的评论样本，风险不能视为0": "No review samples with problem tags obtained, risk cannot be considered 0",
  "出现用户明确不可接受的问题：": "User explicitly unacceptable issues found:",
  "评论来自定向样本，个人加权样本指标不代表总体问题发生率": "Reviews from targeted samples; individual weighted sample metrics do not represent overall issue occurrence rate",
  "未取得绑定人数、日期、餐食、取消条款的房型": "No room type obtained with bound number of people, date, meals, and cancellation terms",
  "房型关键条件未知，尚不能确认取消、人数或外窗要求": "Key room type conditions unknown; cannot confirm cancellation, number of people, or exterior window requirements yet",
  "已核验房型没有满足取消、人数或外窗硬条件的方案": "Verified room types have no options meeting hard conditions for cancellation, number of people, or exterior windows",
  "房型展示价已超预算": "Room type display price exceeds budget",
  "最大入住人数未知": "Maximum occupancy unknown",
  "库存需要待确认或状态未知": "Inventory needs confirmation or status unknown",
  "外窗及采光尚未证实；内窗、暗窗不能等同外窗": "Exterior windows and lighting not yet verified; interior windows and dark windows cannot be equated with exterior windows",
  "高重要度评论问题需核验具体房型或整改证据": "High-importance review issues require verification of specific room types or rectification evidence",
  "最终含税总价、到店费用、报价有效期及库存复核未完成": "Final total price including tax, on-site fees, quote validity period, and inventory review not completed",
  "真实订单、取消、退款接口与购买授权未验证": "Real order, cancellation, refund interfaces and purchase authorization not verified",
  "浏览器人工采集的定向历史样本，非全量或本轮实时评论API": "Browser manually collected targeted historical samples, not full volume or this round's real-time review API",
  "工体北路13号院世茂国际中心2号楼": "Building 2, Shimao International Center, No. 13 Courtyard, Gongti North Road",
  "飞猪网页（历史观察）": "Fliggy website (historical observation)",
  "网页会员优惠适用性未验证": "Web member discount applicability not verified",
  "公交路线": "Bus route",
  "通勤": "Commuting",
  "尚无新的已核验候选": "No new verified candidates yet",
  "保持预算与底线，重新搜索目的地附近酒店；不推定全市场无解": "Maintain budget and bottom line, re-search hotels near destination; do not assume no solution in entire market",
  "新候选、评论、最终含税价与具体通勤待核验": "New candidates, reviews, final tax-included price, and specific commuting to be verified",
  "监控必须使用实时查询，不能把历史回放当新价格": "Monitoring must use real-time queries; cannot treat historical playback as new prices",
  "监控截止须带时区，晚于当前时间且在24小时内": "Monitoring deadline must include timezone, later than current time and within 24 hours",
  "请先等待本轮结束并停止已有监控": "Please wait for this round to end and stop existing monitoring",
  "监控截止，停止查询；未执行真实购买": "Monitoring deadline reached, stop querying; no real purchase executed",
  "本轮查询未完成；历史记录不作当前库存或成交依据。": "This round's query not completed; historical records do not serve as basis for current inventory or transactions.",
  "本会话核验正在运行或已关闭": "This session verification is running or has been closed",
  "核验要求": "Verification requirements",
  "读取带时间戳的历史证据": "Read timestamped historical evidence",
  "雍和宫原案例的报价、路线、评论记录回放；未请求当前库存。": "Playback of Yonghe Palace original case's quotes, routes, and review records; current inventory not requested.",
  "跨平台实时检索": "Cross-platform real-time search",
  "并行查询飞猪与RollingGo；失败的数据源保留错误，不伪造结果。": "Parallel query of Fliggy and RollingGo; failed data sources retain errors, no fabricated results.",
  "飞猪": "Fliggy",
  "位置与通勤核验": "Location and commuting verification",
  "目的地地图查询未完成": "Destination map query not completed",
  "目的地景点坐标未唯一匹配，未猜测坐标": "Destination attraction coordinates not uniquely matched, coordinates not guessed",
  "目的地坐标未核验": "Destination coordinates not verified",
  "酒店名称地址未唯一匹配，路线保持未知": "Hotel name and address not uniquely matched, route remains unknown",
  "地图或路线服务未完成，不把缺失视为0分钟": "Map or route service not completed, missing data not treated as 0 minutes",
  "核验房型": "Verify room types",
  "按通勤、评论与个人规则选最多3家RollingGo候选，逐家获取具体房型。": "Select up to 3 RollingGo candidates based on commuting, reviews, and personal rules, obtain specific room types from each.",
  "房型查询未完成，旧价不作当前可订证据": "Room type query not completed, old prices not used as evidence for current availability",
  "绑定评论来源": "Bind review sources",
  "仅合并酒店身份匹配的既有浏览器评论观察；未知酒店保持无评论证据。历史网页报价没有重用为当前报价。": "Only merge existing browser review observations with matched hotel identities; unknown hotels remain without review evidence. Historical web quotes not reused as current quotes.",
  "固定规则评估": "Fixed rule evaluation",
  "先硬条件与通勤档位，再个人评论样本指标、展示价格与通勤时长；信息缺失不视为满足。": "First hard conditions and commuting tiers, then personal review sample metrics, display prices, and commuting duration; missing information not considered as satisfied.",
  "Jev核验建议": "Jev verification suggestions",
  "模型读取本轮合并的房型、路线、评论与缺口摘要；仅安排下一步证据任务。": "Model reads this round's merged room types, routes, reviews, and gap summary; only arranges next step evidence tasks.",
  "Jev判断未完成；保留固定规则结果，禁止交易。": "Jev judgment not completed; retain fixed rule results, prohibit trading.",
  "仅名称地址完全匹配；未对齐房型、餐食、税费与取消政策，不能直接按价差购买": "Only name and address fully matched; room types, meals, taxes, and cancellation policies not aligned, cannot purchase directly based on price difference",
  "生成条件组合": "Generate condition combinations",
  "最多3套备选条件，所有剩余证据缺口保留；不修改预算与降级权限。": "Maximum 3 sets of alternative conditions, all remaining evidence gaps retained; do not modify budget and downgrade permissions.",
  "交易阻断": "Transaction blocking",
  "全部真实候选不可成交：最终含税价、完整真实购买授权与订单/取消/退款能力未核验；订单和钱包不变。": "All real candidates cannot be transacted: final tax-included price, complete real purchase authorization, and order/cancellation/refund capabilities not verified; orders and wallet unchanged.",
  "已完成证据汇总与规则评估；没有证据完整且可自动购买的候选。检索有数量上限，不能断言全市场无解。": "Evidence summary and rule evaluation completed; no candidates with complete evidence and available for automatic purchase. Search has quantity limit, cannot assert no solution in entire market.",
  "未取得候选；查询失败或无结果不等于整个市场无解。": "No candidates obtained; query failure or no results does not mean no solution in entire market.",
  "会话已关闭，结果未保存": "Session closed, results not saved"
};
