export const englishCore:Record<string,string>={
'只读查询授权已撤销，请重新确认后再查询':'Read-only query consent was withdrawn. Confirm it again before querying.',
'本轮没有新线索可核验，部分失败查询仍在重试等待期；不代表附近没有合适酒店。':'No new leads are eligible in this run. Some failed queries are waiting for retry; this does not establish that nearby hotels are unsuitable.',
'本轮返回的附近线索已观察过；请刷新已有酒店或调整搜索范围，不能认定全市场无解。':'The nearby leads returned in this run were already observed. Refresh existing hotels or revise the search area; this does not establish market-wide absence.',
'附近发现仅核验最多3条新线索；原候选保留在原记录，不能认定覆盖全市场。':'Nearby discovery checks up to three new leads. Previous candidates remain in their original record; this does not cover the whole market.',

'本轮只刷新一家的房型与路线；评论仍为原观察，报价仍需最终核验。':"Only this hotel's rooms and route were refreshed. Reviews keep their original timestamps; booking details still need verification.",
'本轮路线核验未完成，未沿用旧路线判断':'Route verification did not complete; the previous route was not reused.',
'定向刷新酒店':'Refresh this hotel',
'定向刷新结束':'Hotel refresh finished',
'原报价或条款变化，停止该方案监控；请重新核验。':'The quote or its terms changed. Monitoring stopped; verify again.',

'交易演示 · 测试酒店与测试资金':'Transaction demo · Test hotels and test funds','住宿场景':'Accommodation scene','真实能力，已经接通':'Live capabilities, connected','运行真实平台流程 →':'Run the live workflow →','用真实平台数据，完成酒店选择核验':'Verify your hotel choice with live platform data',

'装修气味':'Renovation odors','设施维护':'Facility maintenance','高级大床房':'Superior double room','清途旅行 · 平台 A':'Qitu Travel · Platform A','安心订 · 平台 B':'Staywell · Platform B','旅居精选 · 平台 C':'Port Collection · Platform C',
'没有用户确认的真实购买授权':'No user-confirmed real purchase authorization.','尚未获得绑定房型、人数、餐食的最终含税报价':'No final tax-inclusive quote bound to room type, guests and meal plan.','商户订单、取消与退款接口尚未获准并验证':'Merchant order, cancellation and refund interfaces are not approved and verified.','此示例行程只授权查询和规则验证':'This example trip authorizes queries and rule checks only.','当前 MCP 工具清单未核验下单、取消、退款能力':'Booking, cancellation and refund capabilities have not been verified in the MCP tool list.','缺少最终含税成交报价与完整购买授权':'Final tax-inclusive booking price and complete purchase authorization are missing.',

'跨平台身份匹配':'Cross-platform identity matching','本轮未取得身份一致且条件对齐的跨平台报价，不能宣称找到最低成交价。':'This run has no cross-platform quotes with verified hotel identity and aligned stay conditions. A lowest bookable price has not been established.',
'住得合适，选得轻松':'Stay well. Choose with ease.','我的住宿助手':'My stay assistant','主导航':'Main navigation','选酒店流程':'Hotel selection','任务总览':'Overview','偏好与授权':'Preferences & consent','酒店比较':'Hotel comparison','订单与决策':'Orders & decisions','把选酒店，变简单。':'Find your stay, simply.','告诉我们行程与取舍，剩下的交给住宿助手。':'Tell us your trip and priorities. Your stay assistant takes it from there.','等待授权':'Awaiting consent','行程计划':'Trip planning','查找酒店':'Find hotels','跨平台比较':'Compare platforms','预订结果':'Booking outcome','价格监控':'Price monitoring','待核对':'To review','待确认':'To confirm','待观察':'Not searched','待比较':'Not compared','待成交':'Not booked','未开始':'Not started','已确认':'Confirmed','上一步':'Back','查看下一步':'View next step','先安排好这次行程':'Start with your trip','选酒店，按你的标准来':'Choose on your terms','准备好了，开始找酒店':'Ready to find your stay','价格和体验，放在一起比较':'Compare price and experience','查看你的预订结果':'Review your booking outcome','订好以后，继续留意好价格':'Keep watching for better prices','填写基本信息，下一步再确认偏好。':'Enter your trip details, then confirm your preferences.','告诉我们底线，以及你愿意做的取舍。':'Set your requirements and the compromises you accept.','这次想住在哪里？':'Where would you like to stay?','以主要目的地为中心，帮你找到合适的住宿。':'Find a suitable stay near your main destination.','主要目的地':'Main destination','入住日期':'Check-in date','退房日期':'Check-out date','入住人数':'Guests','房间数量':'Rooms','想住的房型':'Room type','住宿总预算（元）':'Total stay budget (CNY)','全部房间、全部晚数的含税预算，包含累计不可退费用。':'Tax-inclusive budget for all rooms and nights, including accumulated non-refundable costs.','换订时的资金上限':'Maximum temporary funds during replacement','先保存行程，下一步确认偏好与授权':'Save your trip, then confirm preferences and consent','保存行程，下一步':'Save trip & continue','演示时间工具':'Simulation clock','已暂停':'Paused','测试环境 · 上海时间':'Test environment · Shanghai time','仿真交易':'Simulated transactions','真实 API / MCP':'Live API / MCP','真实酒店查询':'Live hotel search','完整只读核验':'Guided live verification','真实数据 · 只读查询':'Live data · read-only','体验仿真平台':'Explore simulated platforms','每一步，都由你做主':'You stay in control','先确认偏好与预算，再开始自动预订。':'Confirm preferences and budget before automatic booking.','体验模式 · 酒店与资金为测试数据，图片为氛围示意':'Demo mode · Hotels and funds are simulated; images are illustrative','所有商户与资金均为仿真数据':'All merchants and funds are simulated','StayPilot · 让预算、偏好与交易边界保持一致':'StayPilot · Keep budget, preferences and transaction permissions aligned',
'一次核验，汇总酒店选择依据':'One workflow. Evidence for your hotel choice.','跨平台检索 → 地图与房型 → 评论证据 → 个人规则 → 条件组合。真实平台只读，不修改购买授权、钱包或订单。':'Search platforms → routes and rooms → review evidence → personal rules → alternatives. Live sources are read-only; no purchase authority, wallet or order changes.','城市':'City','具体目的地':'Destination landmark','入住':'Check-in','退房':'Check-out','成人（1 间房）':'Adults (one room)','含税总预算（元）':'Total budget including tax (CNY)','步行上限（分钟）':'Maximum walking time (minutes)','地铁直达上限（分钟）':'Maximum direct metro time (minutes)','窗型':'Window preference','有窗优先':'Window preferred','必须明确外窗':'Exterior window required','窗型均可':'Any window type','卫生重要度（0—5）':'Hygiene importance (0–5)','隔音重要度（0—5）':'Noise importance (0–5)','允许地铁直达降级':'Allow direct metro as a fallback','必须处于免费取消窗口':'Require a free cancellation window','调用 Jev 建议下一步核验':'Ask Jev for the next verification step','明确不可接受的问题（默认不设置绝对排除）':'Unacceptable issues (no absolute exclusions by default)','仅授权 API / MCP 查询与规则核验，不授权真实购买。':'Authorize API / MCP queries and rule checks only. No real purchase authorization.','下一步：偏好与授权':'Next: preferences & consent','确认只读授权，开始查询':'Confirm read-only consent & continue','请先确认当前行程的只读授权。':'Confirm read-only consent for the current trip first.','运行实时只读核验':'Run live read-only verification','回放雍和宫证据并重新评估':'Replay Yonghe Temple evidence & reassess','真实交易关闭':'Real transactions disabled','真实模式只核验酒店证据。测试资金订单请使用仿真交易流程。':'Live mode verifies hotel evidence. Use the simulation workflow for test-funded orders.','验证后台购买阻断':'Verify backend purchase blocking','真实购买已被后台阻止；没有创建真实订单。':'The backend blocked real purchases. No real orders were created.','以下是上一轮条件的结果，请按当前条件重新核验。':'These results use previous conditions. Run verification again for your current trip.','持续核验当前行程':'Monitor this trip','截止时间（UTC+8）':'Deadline (UTC+8)','开启持续核验':'Start monitoring','停止持续核验':'Stop monitoring','未启用':'Not enabled','尚未运行':'Not run yet','完成':'Complete','正在执行':'Running','本轮规则排除':'Excluded by current rules','待补证据':'More evidence needed','候选与证据缺口':'Candidates & evidence gaps','可重新确认的条件组合':'Alternatives requiring new consent','可核对的执行记录':'Auditable execution record','导出本轮完整核验记录':'Export full verification record','卫生':'Hygiene','隔音':'Noise','气味':'Odor','维护':'Maintenance','服务':'Service','空间':'Space','安全':'Safety','飞猪酒店查询':'Fliggy hotel search','RollingGo 房型核验':'RollingGo room verification'
};
