import {useState,type FormEvent} from 'react';
import type {FlyaiResult} from '../shared/flyai';
import RealTools from './RealTools';
import AmapRoutes from './AmapRoutes';
export default function FlyaiLive(){
 const [destination,setDestination]=useState('杭州'),[poi,setPoi]=useState('西湖'),[checkIn,setCheckIn]=useState('2026-11-06'),[checkOut,setCheckOut]=useState('2026-11-08');
 const [hotelAddress,setHotelAddress]=useState('');
 const [result,setResult]=useState<FlyaiResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function search(e:FormEvent){e.preventDefault();setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/live/fliggy/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({destination,poi,checkIn,checkOut})});const data=await r.json();if(!r.ok)throw new Error(data.error);setResult(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="simulation-banner">飞猪真实数据验证 · 仅搜索与详情跳转 · 未启用真实交易</div><main className="live-page"><header className="section-heading"><div><span className="section-kicker">FLIGGY / LIVE VERIFICATION</span><h1>真实酒店，逐项核验。</h1><p className="hint">官方 FlyAI 搜索 · 密钥保存在服务端 · 本页采用真实执行时间</p></div><div className="journey-buttons"><a className="btn" href="/live/rollinggo">RollingGo 房型核验</a><a className="btn" href="/">返回仿真控制台</a></div></header><form className="panel live-form" onSubmit={search}><label>目的地<input value={destination} onChange={e=>setDestination(e.target.value)} required maxLength={80}/></label><label>附近地点<input value={poi} onChange={e=>setPoi(e.target.value)} maxLength={120}/></label><label>入住<input type="date" value={checkIn} onChange={e=>setCheckIn(e.target.value)} required/></label><label>退房<input type="date" value={checkOut} onChange={e=>setCheckOut(e.target.value)} required/></label><button className="btn primary" disabled={busy}>{busy?'正在查询飞猪…':'查询真实酒店'}</button></form>{error&&<p role="alert" className="panel">{error}</p>}<section className="panel"><h2>成交核验状态：信息不足，阻止自动预订</h2><p>搜索价尚未绑定具体房型、人数、餐食、税费与取消政策。装修时间不能替代开业时间；评分 0 或缺失的含义尚未核验。搜索地点和排序条件也需要在详情页再次确认。</p><p className="hint">真实结果不会进入仿真钱包或测试订单。打开详情链接不会自动创建订单。</p></section><AmapRoutes hotelAddress={hotelAddress}/><RealTools query={{destination,poi,checkIn,checkOut}} onResult={setResult}/>{result&&<><p className="hint">已观察 {result.hotels.length} 家 · {new Date(result.observedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})} 上海时间 · {result.query.checkIn} → {result.query.checkOut}</p><div className="live-hotels">{result.hotels.map((h,i)=><article className="panel live-hotel" key={h.id||i}>{h.image&&<img src={h.image} alt={h.name} referrerPolicy="no-referrer" loading="lazy"/>}<div><span className="section-kicker">飞猪 / {h.id}</span><h2>{h.name}</h2><p>{h.address}</p><button className="text-button" onClick={()=>setHotelAddress(h.address)}>用这个酒店地址核验通勤 →</button><p>{h.nearby||'周边信息未知'}</p><div className="hotel-chips"><span>评分原值 {h.score??'未知'} · 尺度待核验</span><span>装修 {h.decorationTime||'未知'}</span></div><h3>{h.price} <small>平台搜索价 · 含税住宿总价待核验</small></h3><p className="hint">尚缺：{result.missingFields.join('、')}</p>{h.detailUrl&&<a className="btn" href={h.detailUrl} target="_blank" rel="noreferrer">前往飞猪核验详情 ↗</a>}</div></article>)}</div>{result.systemMessage&&<p className="panel">平台提示：{result.systemMessage}</p>}</>}</main></>;
}
