import {useEffect,useState} from 'react';
import type {RollinggoState} from '../shared/rollinggo';
import {JEV_ACTION_LABELS,type JevAssessment} from '../shared/jev';
const defaultFocus='优先核验可取消、有窗的房型；我浅眠，需要卫生与隔音评论证据。这里只安排查证顺序，不改变预算或购买授权。';
export default function JevPanel({state,onRefresh,onInspect}:{state:RollinggoState|null;onRefresh:()=>Promise<unknown>;onInspect:(id:number)=>void}){
 const [focus,setFocus]=useState(defaultFocus),[result,setResult]=useState<JevAssessment|null>(null),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/live/integrations').then(r=>r.json()).then(p=>setConfigured(Boolean(p.jev?.configured))).catch(()=>{});},[]);
 useEffect(()=>{setResult(state?.jevAssessments?.find(r=>r.evidenceKey===state.jevEvidenceKey&&r.focus===focus.trim())??null);},[state,focus]);
 async function assess(){setBusy(true);setError('');try{const r=await fetch('/api/live/jev/assess',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({focus})});const p=await r.json();if(!r.ok)throw new Error(p.error||'未取得新判断');setResult(p);await onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const candidate=result?.answers.candidate_to_inspect,next=result?.answers.next_evidence_action;
 const isCurrent=result?.evidenceKey===state?.jevEvidenceKey&&result?.focus===focus.trim();
 const proposedId=candidate?.choice.startsWith('hotel_')?Number(candidate.choice.slice(6)):null;
 return <section className="panel jev-panel"><span className="section-kicker">TYPESAFE / JEV · EVIDENCE PRIORITY</span><h2>下一步，先查什么？</h2><p>Jev辅助安排查证顺序。预算、降级次序、评论风险计算及取消权限由原有规则控制；建议不代表酒店已合格。</p><label>本轮核验关注点<textarea value={focus} maxLength={1500} disabled={busy} onChange={e=>setFocus(e.target.value)}/></label><div className="journey-buttons"><button className="btn primary" disabled={busy||!configured||!state?.searches[0]?.hotels.length} onClick={()=>void assess()}>{busy?'Jev正在判断…':'让Jev安排核验优先级'}</button><span className="hint">{configured?'本机已配置TypeSafe':'未配置TypeSafe'} · 只使用本会话已观察的候选</span></div>{error&&<p role="alert">{error}</p>}
 {result&&candidate&&next&&<><p className="hint">真实模型 {result.model} · 判断时间 {new Date(result.observedAt).toLocaleString('zh-CN',{timeZone:'Asia/Hong_Kong'})} 香港时间 · {result.elapsedMs}ms · 输入 {result.usage.input_tokens} / 输出 {result.usage.output_tokens} tokens</p><div className="jev-decisions"><article><h3>优先补查的候选</h3><strong>{result.candidateLabels[candidate.choice]}</strong><p>置信度 {Math.round(candidate.confidence*100)}%</p>{Object.entries(candidate.probabilities).sort((a,b)=>b[1]-a[1]).map(([id,p])=><div className="jev-probability" key={id}><span>{result.candidateLabels[id]}</span><meter min="0" max="1" value={p}/><span>{(p*100).toFixed(1)}%</span></div>)}{proposedId!==null&&<button className="btn" disabled={!isCurrent||busy} onClick={()=>onInspect(proposedId)}>手动核验这家酒店的房型</button>}</article><article><h3>当前酒店的下一项证据</h3><p>{result.selectedHotelName}</p><strong>{JEV_ACTION_LABELS[next.choice as keyof typeof JEV_ACTION_LABELS]}</strong><p>置信度 {Math.round(next.confidence*100)}%</p>{Object.entries(next.probabilities).sort((a,b)=>b[1]-a[1]).map(([id,p])=><div className="jev-probability" key={id}><span>{JEV_ACTION_LABELS[id as keyof typeof JEV_ACTION_LABELS]}</span><meter min="0" max="1" value={p}/><span>{(p*100).toFixed(1)}%</span></div>)}</article></div><p className="hint">来源搜索观察：{new Date(result.sourceObservedAt).toLocaleString('zh-CN',{timeZone:'Asia/Hong_Kong'})}。两个问题独立判断：候选优先级与当前酒店的下一步可能指向不同酒店。概率表达模型判断，置信度不是正确率或购买许可；未执行动作、未创建订单。</p><details><summary>核对输入事实与问题选项</summary><pre className="jev-request">{JSON.stringify(result.request,null,2)}</pre></details></>}
 {!state?.searches[0]?.hotels.length&&<p className="hint">先查询酒店，才能基于真实候选判断。</p>}
 </section>;
}
