import {useEffect,useRef,useState} from 'react';
import {pick} from './i18n';
type Setup={fliggy:boolean;rollinggo:boolean;amap:boolean;jev:boolean};
export function QueryReadiness(){
 const [setup,setSetup]=useState<Setup|null>(null),[loading,setLoading]=useState(false),[failed,setFailed]=useState(false);const pending=useRef<AbortController|null>(null);
 async function load(){if(pending.current)return;const controller=new AbortController();pending.current=controller;setLoading(true);setFailed(false);
 try{const response=await fetch('/api/live/integrations',{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(10000)])});if(!response.ok)throw Error('Configuration unavailable');const data=await response.json();const values=Object.fromEntries(['fliggy','rollinggo','amap','jev'].map(key=>[key,data[key]?.configured]));if(Object.values(values).some(value=>typeof value!=='boolean'))throw Error('Incomplete configuration');if(pending.current===controller)setSetup(values as Setup);
 }catch{if(pending.current===controller&&!controller.signal.aborted){setSetup(null);setFailed(true);}}finally{if(pending.current===controller){pending.current=null;setLoading(false);}}
 }
 useEffect(()=>{void load();return()=>{pending.current?.abort();pending.current=null;};},[]);
 const names={fliggy:'Fliggy FlyAI',rollinggo:'RollingGo MCP',amap:'Amap',jev:'Jev / TypeSafe'};
 return <div role="region" aria-label="Live service configuration"><h3>{pick('查询前的服务配置','Service setup before searching')}</h3><p className="lw-hint">{pick('这里只检查服务端是否配置凭证，不代表登录成功、服务连通、接口权限或报价有效。','This checks server credential configuration only. It does not establish successful login, connectivity, API permissions or valid prices.')}</p>{loading&&<p>{pick('读取配置状态…','Reading configuration…')}</p>}{failed&&<p role="alert">{pick('配置状态无法核验，请检查本地服务后重试。','Configuration could not be verified. Check the local service and retry.')}</p>}{setup&&<><ul>{Object.entries(setup).map(([key,configured])=><li key={key}>{names[key as keyof Setup]} · {configured?pick('已配置凭证','Credentials configured'):pick('尚未配置凭证','Credentials not configured')}</li>)}</ul>{!setup.fliggy&&!setup.rollinggo&&<p>{pick('酒店查询凭证均未配置，实时检索无法使用；可查看历史证据。','Neither hotel provider is configured. Live hotel search is unavailable; historical evidence remains accessible.')}</p>}{!setup.amap&&<p>{pick('缺少地图配置，通勤证据无法自动补齐。','Map setup is missing; commute evidence cannot be fetched automatically.')}</p>}{!setup.jev&&<p>{pick('Jev尚未配置，规则检查仍可使用，但不会取得模型取舍建议。','Jev is not configured. Rule checks remain available, but model tradeoff advice will be unavailable.')}</p>}</>}<p>{pick('真实预订、支付、取消和退款尚未开放。','Real booking, payment, cancellation and refunds are not enabled.')}</p><button className="secondary" disabled={loading} onClick={()=>void load()}>{pick('重新检查配置','Recheck configuration')}</button></div>;
}
