import {EvidenceTime} from './EvidenceTime';
import type {QuoteRecheck} from '../shared/tradeoffs';
import {pick} from './i18n';
export function QuoteRecheckCard({quote:q}:{quote:QuoteRecheck}){
 const labels={unchanged:pick('展示价未变化','Displayed price unchanged'),price_changed:pick('展示价发生变化','Displayed price changed'),terms_changed:pick('房型或方案条款变化／不可比，不能计算节省','Room or plan terms changed or incomparable; savings cannot be calculated'),not_found:pick('本次未找到原报价','Original quote not found in this response'),failed:pick('复核请求失败或价格口径不足','Recheck failed or comparable price unavailable')};
 const guidance={unchanged:pick('只确认这次展示估价未变化；最终费用和库存仍待核验。','Only the displayed estimate is unchanged. Final charges and inventory still require verification.'),price_changed:pick('这是同条款展示估价的变化，不是最终成交价或已实现节省。','This is a change in the same-terms display estimate, not a final booking price or realized saving.'),terms_changed:pick('请重新核验具体房型、餐食和取消政策，不沿用原方案。','Recheck the room, meals and cancellation policy before using this option again.'),not_found:pick('不能据此断定售罄。请刷新这家酒店，重新选择当前报价；不会自动替换房型。','This does not establish that the hotel is sold out. Refresh this hotel and select a current quote; no room is automatically substituted.'),failed:pick('没有取得可靠的新结论，旧价不能作为当前可订证据。可稍后手动重试。','No reliable new conclusion was obtained. The old price does not establish current availability. Retry manually later.')};
 const comparable=(q.status==='unchanged'||q.status==='price_changed')&&q.deltaCents!==null;
 return <article><h3>{q.hotelName}</h3><p><b>{labels[q.status]}</b></p><p>{q.before.roomName}</p>{q.before.ratePlanName&&<p>{pick('原报价方案','Previous rate plan')}: {q.before.ratePlanName}</p>}{q.after?.ratePlanName&&q.after.ratePlanName!==q.before.ratePlanName&&<p>{pick('本次报价方案','Current rate plan')}: {q.after.ratePlanName}</p>}<p>{pick('复核执行时间（上海）','Checked at (Shanghai)')}: {<EvidenceTime value={q.checkedAt}/>}</p><p>{pick('价格比较基准','Comparison baseline observation')}: {<EvidenceTime value={q.beforeObservedAt}/>} · {q.before.estimatedStayPrice??'—'} {q.before.currency??pick('币种未知','Currency unverified')}</p>{q.after&&<p>{pick('本次报价观察','Current quote observation')}: {<EvidenceTime value={q.afterObservedAt}/>} · {q.after.estimatedStayPrice??'—'} {q.after.currency??pick('币种未知','Currency unverified')}</p>}{q.baseline&&<p className="lw-hint">{q.baseline.kind==='recheck'?pick('基准为最近一次取得有效价格的复核。','The baseline is the most recent recheck with a usable price.'):pick('基准为原查询报价。','The baseline is the original query observation.')}{q.baseline.skippedAttempts>0&&<> {pick('中间未取得有效价格的复核次数','Intervening checks without a usable price')}: {q.baseline.skippedAttempts}. {pick('差额不是与这些空结果之间的涨跌。','The difference is not a change against those empty results.')}</>}</p>}{comparable&&<p>{pick('展示估价变化','Display estimate change')}: {q.deltaCents!>0?'+':''}{(q.deltaCents!/100).toFixed(2)} CNY</p>}<p className="lw-hint">{guidance[q.status]}</p></article>;
}
