import {useEffect,useState,useRef} from 'react';
import type {FlyaiQuery,FlyaiResult} from '../shared/flyai';
import type {RealState} from '../shared/real-agent';
type Evidence=typeof import('../server/fliggy-evidence').fliggyEvidence;
type Assessment=ReturnType<typeof import('../server/fliggy-evidence').reviewAssessment>;
const labels:Record<string,string>={noise:'隔音',hygiene:'清洁',smell:'气味',maintenance:'设施',service:'服务',space:'空间',security:'夜间安全体验'};
async function request<T>(path:string,payload?:unknown){const r=await fetch(path,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:undefined);const data=await r.json();if(!r.ok)throw new Error(data.error||'操作未完成');return data as T;}
export default function RealTools({query,onResult}:{query:FlyaiQuery;onResult:(r:FlyaiResult)=>void}){
 const [state,setState]=useState<RealState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [profile,setProfile]=useState('sensitive'),[evidence,setEvidence]=useState<{evidence:Evidence;assessment:Assessment}|null>(null);
 const [providers,setProviders]=useState<{id:string;name:string;configured:boolean;status:string}[]>([]);
 const [deadline,setDeadline]=useState(()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(Date.now()+6*3600000)).replace(' ','T'));
 async function refresh(){const data=await request<RealState>('/api/live/fliggy/state');setState(data);}
 useEffect(()=>{void refresh().catch(()=>{});const timer=setInterval(()=>void refresh().catch(()=>{}),5000);void request<typeof providers>('/api/live/providers').then(setProviders).catch(()=>{});return()=>clearInterval(timer);},[]);
 useEffect(()=>{const controller=new AbortController();fetch('/api/live/fliggy/evidence/72547102?profile='+profile,{signal:controller.signal}).then(r=>r.json()).then(setEvidence).catch(()=>{});return()=>controller.abort();},[profile]);
 async function monitor(enabled:boolean){setBusy(true);setError('');try{const data=await request<RealState>('/api/live/fliggy/monitor',{...query,enabled,deadline:deadline+':00+08:00'});setState(data);if(enabled&&data.snapshots[0])onResult(data.snapshots[0]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function blocked(){try{const r=await fetch('/api/live/fliggy/book',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const data=await r.json();setError('实际交易阻断：'+data.reasons.join('；'));await refresh();}catch{setError('无法取得阻断结果');}}
 const latest=state?.snapshots[0];
 const delivered=useRef('');
 useEffect(()=>{if(latest&&state?.monitor.enabled&&latest.observedAt!==delivered.current&&JSON.stringify(latest.query)===JSON.stringify(query)){delivered.current=latest.observedAt;onResult(latest);}},[latest,state?.monitor.enabled,query,onResult]);
 return <><section className="panel real-tools"><h2>真实价格监控 · 每 30 分钟检查</h2><p className="hint">使用真实上海时间；截止自动停止。后台服务与电脑需保持运行，重启后须重新启用监控。</p><div className="live-form"><label>查询截止（上海时间）<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} disabled={state?.monitor.enabled}/></label><button className="btn primary" disabled={busy} onClick={()=>void monitor(!state?.monitor.enabled)}>{state?.monitor.enabled?'停止真实监控':'启用仅查询监控'}</button><button className="btn" onClick={()=>void blocked()}>验证真实交易阻断</button></div><p>{state?.monitor.enabled?'监控运行中':'监控未启用'}{state?.monitor.nextCheckAt&&' · 下次检查 '+new Date(state.monitor.nextCheckAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p>{state?.monitor.lastError&&<p>{state.monitor.lastError}</p>}{latest&&<p className="hint">持久化观察 {state?.snapshots.length} 轮 · 最近一次 {new Date(latest.observedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p>}{error&&<p role="alert">{error}</p>}{state&&state.snapshots.length>0&&<details><summary>核对价格变化与决策记录</summary><div className="live-history">{state.snapshots.slice(0,8).map((s,i)=><p key={i}>{new Date(s.observedAt).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai'})} · {s.query.destination} {s.query.checkIn}→{s.query.checkOut} · {s.hotels.slice(0,3).map(h=>h.name+' '+h.price).join('；')}</p>)}{state.events.slice(0,8).map((e,i)=><p key={'e'+i}>{e.action}：{e.reason}</p>)}</div></details>}</section>
 <section className="panel real-tools"><h2>已浏览核验的评论证据 · 汉庭黄龙文三路</h2><p className="hint">此处是 2026-10-04 浏览得到的历史证据，不是实时评论 API。其他酒店仍需逐家核验。</p>{evidence&&<><p>网页评分 {evidence.evidence.webScore}，API 原值 {evidence.evidence.apiScore}；网页 {evidence.evidence.reviewCount} 条点评、差评标签 {evidence.evidence.negativeTabCount} 条。2022 年开业 / 装修。</p><p>{evidence.evidence.warning}</p><div className="live-form"><label>容忍度演示（不构成购买授权）<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="sensitive">浅眠：不能接受历史隔音、清洁或气味投诉</option><option value="flexible">宽容：可接受隔音和空间代价，清洁仍是底线</option></select></label></div><p>选定样本风险分：{evidence.assessment.risk.toFixed(2)} · 示例底线冲突：{evidence.assessment.excludedBy.map(i=>labels[i]).join('、')||'无'}</p><div className="hotel-chips">{evidence.assessment.rows.filter(r=>r.count>0).map(r=><span key={r.issue}>{labels[r.issue]} {r.count}/{r.sampleSize} × 权重 {r.weight}</span>)}</div><p className="hint">比例分母是筛选出的 10 条差评，不代表全部 218 条评论或未来入住风险；旧评论可能重复。同一问题因权重不同产生不同分数。</p><details><summary>查看 10 条负评样本的日期、依据及正面反证</summary>{evidence.evidence.selectedReviews.map((r,i)=><article className="review" key={i}><strong>{r.date}</strong><p>{r.summary}{r.excerpt&&<> · 原文节选「{r.excerpt}」</>}</p></article>)}{evidence.evidence.positiveEvidence.map((r,i)=><p key={i}>正面反证 {r.date}：{r.summary}</p>)}</details><p>已观察房型：{evidence.evidence.observedRoom.room} · {evidence.evidence.observedRoom.area} · {evidence.evidence.observedRoom.displayPrice}（网页显示价）。取消：{evidence.evidence.observedRoom.cancellation}</p><p className="hint">这是一份历史房型观察，最终含税总价、餐食及退款到账仍未确认，不能自动成交。</p><a className="btn" href={evidence.evidence.sourceUrl} target="_blank" rel="noreferrer">打开飞猪原评论与房型页 ↗</a></>}</section>
 <section className="panel real-tools"><h2>官方数据源与申请状态</h2>{providers.map(p=><p key={p.id}><strong>{p.name}</strong> · {p.configured?'本机已配置凭证':'未配置凭证'} · {p.status}</p>)}</section></>;
}
