import {useEffect,useState,type FormEvent} from 'react';
import type {RollinggoQuery,RollinggoFilter,RollinggoSearch,RollinggoDetail,RollinggoState,RollinggoDiscovery} from '../shared/rollinggo';
import AmapRoutes from './AmapRoutes';
const time=(v:string)=>new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'});
const money=(v:number|null,currency:string|null)=>v===null?'未提供':`${currency==='CNY'?'¥':currency||'币种未知 '}${v.toFixed(2)}`;
async function request<T>(path:string,input?:unknown):Promise<T>{const r=await fetch(path,input===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const p=await r.json();if(!r.ok)throw new Error(p.error||p.reasons?.join('；')||'查询未完成');return p;}
const initial:RollinggoQuery={destination:'杭州',poi:'西湖',checkIn:'2026-11-06',checkOut:'2026-11-08',adultCount:2,roomCount:1,childCount:0,size:5};
export default function RollinggoLive(){
 const [query,setQuery]=useState(initial),[result,setResult]=useState<RollinggoSearch|null>(null),[detail,setDetail]=useState<RollinggoDetail|null>(null),[state,setState]=useState<RollinggoState|null>(null),[discovery,setDiscovery]=useState<RollinggoDiscovery|null>(null);
 const [filter,setFilter]=useState<RollinggoFilter>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[hotelAddress,setHotelAddress]=useState('');
 async function refresh(){const s=await request<RollinggoState>('/api/live/rollinggo/state');setState(s);setDiscovery(s.discovery);return s;}
 useEffect(()=>{void refresh().then(s=>{if(s.searches[0]){setResult(s.searches[0]);setQuery(s.searches[0].query);}if(s.details[0])setDetail(s.details[0]);}).catch(()=>{});},[]);
 async function act(work:()=>Promise<void>){setBusy(true);setError('');try{await work();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function search(e:FormEvent){e.preventDefault();setResult(null);setDetail(null);void act(async()=>setResult(await request('/api/live/rollinggo/search',query)));}
 function readDetail(hotelId:number){if(!result)return;setDetail(null);void act(async()=>setDetail(await request('/api/live/rollinggo/detail',{...result.query,hotelId,filter})));}
 const stale=result&&(Object.keys(query) as (keyof RollinggoQuery)[]).some(key=>query[key]!==result.query[key]);
 return <><div className="simulation-banner">RollingGo 真实 MCP · 查询与房型核验 · 真实订单和支付未启用</div><main className="live-page"><header className="section-heading"><div><span className="section-kicker">ROLLINGGO / STREAMABLE HTTP</span><h1>从搜索价，核验到房型。</h1><p className="hint">密钥只在服务端 · 真实上海时间 · 1间房、无儿童；人数默认2成人</p></div><div className="journey-buttons"><a className="btn" href="/live/fliggy">飞猪真实验证</a><a className="btn" href="/">仿真控制台</a></div></header>
 <section className="panel"><h2>MCP 连接与权限</h2><button className="btn" disabled={busy} onClick={()=>void act(async()=>setDiscovery(await request('/api/live/rollinggo/discover',{})))}>验证连接与工具权限</button><button className="btn" disabled={busy} onClick={()=>void act(async()=>{await request('/api/live/rollinggo/book',{});})}>验证真实交易阻断</button>{discovery?<><p>鉴权成功 · {discovery.server?.name} · {time(discovery.verifiedAt)} 上海时间</p><div className="hotel-chips">{discovery.tools.map(t=><span key={t.name}>{t.name} · {t.readOnlyEnabled?'只读已启用':'禁止转发'}</span>)}</div></>:<p className="hint">点击核验以确认这份凭证当前开放的工具；配置凭证不等于鉴权成功。</p>}<p className="hint">只有搜索、详情和标签查询可被转发；未开放自动下单。</p></section>
 <form className="panel live-form" onSubmit={search}><label>目的地<input value={query.destination} maxLength={80} required disabled={busy} onChange={e=>setQuery({...query,destination:e.target.value})}/></label><label>附近景点<input value={query.poi} maxLength={120} disabled={busy} onChange={e=>setQuery({...query,poi:e.target.value})}/></label><label>入住<input type="date" value={query.checkIn} required disabled={busy} onChange={e=>setQuery({...query,checkIn:e.target.value})}/></label><label>退房<input type="date" value={query.checkOut} required disabled={busy} onChange={e=>setQuery({...query,checkOut:e.target.value})}/></label><label>每间成人<input type="number" min="1" max="4" value={query.adultCount} disabled={busy} onChange={e=>setQuery({...query,adultCount:Number(e.target.value)})}/></label><button className="btn primary" disabled={busy}>{busy?'正在核验…':'查询 RollingGo 酒店'}</button></form>
 {error&&<p className="panel" role="alert">{error}</p>}
 <section className="panel"><h2>搜索 → 房型 → 取消条款 → 成交边界</h2><p>星级是酒店等级，不能作为住客评分。搜索价格按每晚展示；房型平均价乘以晚数仅为暂算住宿价，尚缺含税总价和全部费用。库存、评论及开业时间仍需继续核验。</p><p className="hint">不会自动把 RollingGo 与飞猪的同名酒店视为同一家，也不会把搜索最低价与不同餐食或取消条款的房型直接比较。</p></section>
 {result&&<><p className="hint">{result.hotels.length} 家酒店 · 观察 {time(result.observedAt)} 上海时间 · {result.query.checkIn} → {result.query.checkOut} · {result.query.adultCount} 成人 / 1间{stale?' · 表单已改变，以下仍是上次条件的观察':''}</p><section className="panel live-form"><label>房型取消政策<select value={filter.cancelPolicy||''} disabled={busy} onChange={e=>setFilter({...filter,cancelPolicy:(e.target.value||undefined) as RollinggoFilter['cancelPolicy']})}><option value="">全部，保留原条款</option><option value="CANCELABLE">免费取消条款可核验</option><option value="NON_CANCELABLE">不可退款</option></select></label><label>餐食<select value={filter.mealType||''} disabled={busy} onChange={e=>setFilter({...filter,mealType:(e.target.value||undefined) as RollinggoFilter['mealType']})}><option value="">全部</option><option value="NO_MEAL">不含早餐</option><option value="WITH_BREAKFAST">含早餐</option><option value="SINGLE_BREAKFAST">单份早餐</option><option value="DOUBLE_BREAKFAST">双份早餐</option></select></label><p className="hint">修改筛选后，重新点击酒店的房型核验按钮。</p></section><div className="live-hotels">{result.hotels.map(h=><article className="panel live-hotel" key={h.id}>{h.image&&<img src={h.image} alt={h.name} loading="lazy" referrerPolicy="no-referrer"/>}<div><span className="section-kicker">RollingGo / {h.id}</span><h2>{h.name}</h2><p>{h.address}</p><div className="hotel-chips"><span>酒店星级 {h.starRating??'未知'} · 住客评分未知</span>{h.tags.slice(0,5).map(t=><span key={t}>{t}</span>)}</div><h3>{money(h.nightlyPrice,h.currency)} / 晚 <small>平台搜索展示价</small></h3><p>{h.priceMessage}</p><div className="journey-buttons"><button className="btn primary" disabled={busy} onClick={()=>readDetail(h.id)}>核验房型与取消政策</button><button className="btn" onClick={()=>setHotelAddress(h.address)}>核验高德通勤</button>{h.detailUrl&&<a className="btn" href={h.detailUrl} target="_blank" rel="noreferrer">打开平台详情 ↗</a>}</div></div></article>)}</div></>}
 {detail&&<section className="panel rollinggo-detail"><span className="section-kicker">ROOM RATE OBSERVATION</span><h2>{detail.name} · 房型报价</h2><p>{detail.query.checkIn} → {detail.query.checkOut} · {detail.query.adultCount} 成人 / 1间 · {time(detail.observedAt)} 上海时间</p><p className="hint">当前观察筛选：{detail.filter.cancelPolicy||'全部取消政策'} · {detail.filter.mealType||'全部餐食'}。这是历史观察，不代表提交时的库存或价格。</p>{detail.rooms.length===0?<p>本轮没有返回可核验且符合筛选的房型；不能推断所有房型售罄。</p>:detail.rooms.map((r,i)=><article className="review" key={r.ratePlanId||i}><h3>{r.roomName}</h3><p>{r.bedType||'床型未知'} · {r.hasWindow===null?'窗型未知':r.hasWindow?'有窗':'无窗'} · 最大入住 {r.maxOccupancy??'未知'} 人 · {r.size||'面积未知'}{r.size?'平方米':''}</p><p>{r.mealType||'餐食未知'} · 早餐份数 {r.mealAmount??'未知'}</p><strong>平均 {money(r.averagePrice,r.currency)} / 晚 · 暂算 {money(r.estimatedStayPrice,r.currency)} / {Math.round((Date.parse(detail.query.checkOut)-Date.parse(detail.query.checkIn))/86400000)} 晚</strong><p>取消原文：{r.cancelPolicy||'未提供'}</p><p>{r.cancellationStatus==='free_until'?`免费取消截止 ${time(r.cancelUntil!)} 上海时间（杭州酒店当地时间）`:r.cancellationStatus==='nonrefundable'?'不可退款；当前没有真实购买授权':'取消政策或酒店时区未能完整核验'}</p><p className="hint">{r.onRequest===null?'可售状态未知':r.onRequest?'需要商户二次确认':'接口未标记需二次确认；仍须成交前复核'} · 尚缺：{r.missingFields.join('、')}</p></article>)}<p className="hint">成交核验仍未完成：{detail.missingFields.join('、')}。真实交易持续阻断。</p></section>}
 <AmapRoutes hotelAddress={hotelAddress}/>
 {state&&<section className="panel"><h2>观察记录</h2><p>已保存 {state.searches.length} 轮搜索、{state.details.length} 次房型核验；刷新后保留带时间的历史观察。</p><details><summary>查看查询与阻断依据</summary>{state.events.map((e,i)=><p key={i}>{time(e.at)} · {e.action}：{e.reason}</p>)}</details></section>}
 </main></>;
}
