import {useEffect,useState} from 'react';
import type {WorkflowResult} from '../shared/live-workflow';
import {pick} from './i18n';
export function SavedRuns({parentRunId}:{parentRunId?:string}={}){
 const [runs,setRuns]=useState<WorkflowResult[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 async function load(){setBusy(true);setError('');try{const response=await fetch('/api/live/workflow/runs');if(!response.ok)throw new Error();const data=await response.json();setRuns(data);setLoaded(true);}catch{setError(pick('历史记录暂时无法读取，请重试。','Saved runs could not be loaded. Please retry.'));}finally{setBusy(false);}}
 useEffect(()=>{if(!parentRunId){setRuns([]);setLoaded(false);setBusy(false);setError('');return;}const controller=new AbortController();setBusy(true);setError('');setRuns([]);setLoaded(false);
 void fetch('/api/live/workflow/runs?runId='+encodeURIComponent(parentRunId),{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();const data=await response.json();if(!controller.signal.aborted){setRuns(data);setLoaded(true);}}).catch(()=>{if(!controller.signal.aborted)setError(pick('原方案暂时无法读取，请重试。','The previous assessment could not be loaded. Please retry.'));}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[parentRunId]);
 function download(run:WorkflowResult){const url=URL.createObjectURL(new Blob([JSON.stringify(run,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='staypilot-saved-'+run.id+'.json';anchor.click();URL.revokeObjectURL(url);}
 return <section><h2>{pick('之前的查询记录','Previous assessments')}</h2><p>{pick('仅显示当前会话保存的记录，旧价格不代表当前可订。打开历史记录不会修改当前行程、偏好或授权。','Only records saved in this session are shown. Old prices do not prove current availability. Viewing history does not change your trip, preferences or consent.')}</p><button className="secondary" disabled={busy} onClick={()=>void load()}>{busy?pick('正在读取…','Loading…'):pick('查看最近记录','Show recent records')}</button>{error&&<p role="alert">{error}</p>}{parentRunId&&<p className="lw-hint">{pick('以下自动展开原方案，方便补查后回看其他候选；旧证据保留原时间，不能与新报价宣称节省。','The previous assessment opens here so you can review other candidates after a refresh. Old evidence retains its original time and does not establish savings against new quotes.')}</p>}{loaded&&!runs.length&&<p>{parentRunId?pick('当前会话中未找到原方案记录，请查看最近记录。','The previous assessment was not found in this session. Try the recent-records list.'):pick('还没有保存的查询记录。','No saved assessments yet.')}</p>}{runs.map(run=><details key={run.id} data-run-id={run.id} open={run.id===parentRunId} data-parent-run={run.id===parentRunId?run.id:undefined}><summary>{new Date(run.completedAt).toLocaleString()} · {run.query.destination} / {run.query.poi} · {run.kind==='nearby_discovery'?pick('附近新发现','Nearby discovery'):run.kind==='candidate_refresh'?pick('单酒店刷新','Hotel refresh'):run.kind==='reevaluation'?pick('偏好重评','Preference reevaluation'):pick('查询','Search')}</summary><p>{run.query.checkIn} → {run.query.checkOut} · {run.query.adultCount} {pick('成人','adults')} · {pick('预算上限','Budget ceiling')} ¥{run.policy.budgetCents/100}</p><p>{run.mode==='recorded'?pick('历史案例回放','Case replay'):pick('当时取得的接口观察','API observations from that time')} · {pick('证据基准','Evidence as of')} {new Date(run.evidenceAsOf).toLocaleString()}</p><ul>{run.candidates.map(d=><li key={d.candidate.key}>{d.candidate.name} · {d.candidate.source} · {pick('展示估价','Display estimate')} ¥{d.representativeRoom?.estimatedStayPrice??d.candidate.displayPrice??'—'} · {d.minutes??'—'} min · {pick('待核验项','Evidence gaps')} {d.gaps.length}</li>)}</ul><button className="secondary" onClick={()=>download(run)}>{pick('导出原记录','Export original record')}</button></details>)}</section>;
}
