import {savedRunsResponse} from '../shared/saved-runs';
import {displayPriceCents} from '../shared/display-money';
import {useEffect,useRef,useState} from 'react';
import type {WorkflowResult} from '../shared/live-workflow';
import {pick} from './i18n';
import {EvidenceTime} from './EvidenceTime';
export function SavedRuns({parentRunId}:{parentRunId?:string}={}){
 const [runs,setRuns]=useState<WorkflowResult[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const pending=useRef<AbortController|null>(null);
 async function load(expected?:string){
 pending.current?.abort();const controller=new AbortController();pending.current=controller;setBusy(true);setError('');setRuns([]);setLoaded(false);
 try{const response=await fetch('/api/live/workflow/runs'+(expected?'?runId='+encodeURIComponent(expected):''),{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(10000)])});if(!response.ok)throw Error('History unavailable');const data=savedRunsResponse(await response.json(),expected);if(pending.current===controller){setRuns(data);setLoaded(true);}}
 catch{if(pending.current===controller&&!controller.signal.aborted)setError(expected?pick('原方案暂时无法读取，请重试。','The previous assessment could not be loaded. Please retry.'):pick('历史记录暂时无法读取，请重试。','Saved runs could not be loaded. Please retry.'));}
 finally{if(pending.current===controller){pending.current=null;setBusy(false);}}
 }
 useEffect(()=>{if(parentRunId)void load(parentRunId);else{pending.current?.abort();pending.current=null;setRuns([]);setLoaded(false);setBusy(false);setError('');}return()=>{pending.current?.abort();pending.current=null;};},[parentRunId]);
 const estimate=(value:unknown)=>{const cents=displayPriceCents(value);return cents===null?'—':String(cents/100);};
 function download(run:WorkflowResult){const url=URL.createObjectURL(new Blob([JSON.stringify(run,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='staypilot-saved-'+run.id+'.json';anchor.click();URL.revokeObjectURL(url);}
 return <section><h2>{pick('之前的查询记录','Previous assessments')}</h2><p>{pick('仅显示当前会话保存的记录，旧价格不代表当前可订。打开历史记录不会修改当前行程、偏好或授权。','Only records saved in this session are shown. Old prices do not prove current availability. Viewing history does not change your trip, preferences or consent.')}</p><button className="secondary" disabled={busy} onClick={()=>void load()}>{busy?pick('正在读取…','Loading…'):pick('查看最近记录','Show recent records')}</button>{error&&<><p role="alert">{error}</p>{parentRunId&&<button className="secondary" disabled={busy} onClick={()=>void load(parentRunId)}>{pick('重试原方案','Retry previous assessment')}</button>}</>}{parentRunId&&<p className="lw-hint">{pick('以下自动展开原方案，方便补查后回看其他候选；旧证据保留原时间，不能与新报价宣称节省。','The previous assessment opens here so you can review other candidates after a refresh. Old evidence retains its original time and does not establish savings against new quotes.')}</p>}{loaded&&!runs.length&&<p>{parentRunId?pick('当前会话中未找到原方案记录，请查看最近记录。','The previous assessment was not found in this session. Try the recent-records list.'):pick('还没有保存的查询记录。','No saved assessments yet.')}</p>}{runs.map(run=><details key={run.id} data-run-id={run.id} open={run.id===parentRunId} data-parent-run={run.id===parentRunId?run.id:undefined}><summary><EvidenceTime value={run.completedAt}/> · {run.query.destination} / {run.query.poi} · {run.kind==='nearby_discovery'?pick('附近新发现','Nearby discovery'):run.kind==='candidate_refresh'?pick('单酒店刷新','Hotel refresh'):run.kind==='reevaluation'?pick('偏好重评','Preference reevaluation'):pick('查询','Search')}</summary><p>{run.query.checkIn} → {run.query.checkOut} · {run.query.adultCount} {pick('成人','adults')} · {pick('预算上限','Budget ceiling')} ¥{run.policy.budgetCents/100}</p><p>{run.mode==='recorded'?pick('历史案例回放','Case replay'):pick('当时取得的接口观察','API observations from that time')} · {pick('证据基准','Evidence as of')} <EvidenceTime value={run.evidenceAsOf}/></p><ul>{run.candidates.map(d=><li key={d.candidate.key}>{d.candidate.name} · {d.candidate.source} · {pick('展示估价','Display estimate')} ¥{estimate(d.representativeRoom?.estimatedStayPrice??d.candidate.displayPrice)} · {d.minutes??'—'} min · {pick('待核验项','Evidence gaps')} {d.gaps.length}</li>)}</ul><button className="secondary" onClick={()=>download(run)}>{pick('导出原记录','Export original record')}</button></details>)}</section>;
}
